### ISSUE TITLE
does not work on mac with python 2.7

### ISSUE THREAD

**Issue by jrwren** [juju/charm-tools#139]
```
$ virtual ~/t
$ . ~/t/bin/activate
$ pip install charm-tools
$ charm-add
Traceback (most recent call last):
  File "/Users/jrwren/t/bin/charm-add", line 7, in <module>
    from charmtools.generate import main
  File "/Users/jrwren/t/lib/python2.7/site-packages/charmtools/generate.py", line 25, in <module>
    from charms import Charm
  File "/Users/jrwren/t/lib/python2.7/site-packages/charmtools/charms.py", line 13, in <module>
    from launchpadlib.launchpad import Launchpad
  File "/Users/jrwren/t/lib/python2.7/site-packages/launchpadlib/launchpad.py", line 33, in <module>
    from lazr.restfulclient.resource import (
  File "/Users/jrwren/t/lib/python2.7/site-packages/lazr/restfulclient/resource.py", line 36, in <module>
    import simplejson
ImportError: No module named simplejson
```

It looks like the actual problem is in a dependency, but I pip installed charm-tools and it didn't work, so I'm filing this here.

**Comment by marcoceppi** [comment]
you should brew install it. 2.0 beta isn't in there yet but it will be at
release time
