### ISSUE TITLE
does not work on mac with python 3.5

### ISSUE THREAD

**Issue by jrwren** [juju/charm-tools#140]
```
$ virtualenv -p `which python3` .
$ . bin/activate
$ pip install charm-tools==2.0b1
Downloading/unpacking charm-tools==2.0b1
  Downloading charm-tools-2.0b1.tar.gz (112kB): 112kB downloaded
  Running setup.py (path:/Users/jrwren/go/src/github.com/juju/charmstore-client/build/charm-tools/setup.py) egg_info for package charm-tools

    warning: no previously-included files matching '*.pyc' found under directory 'charmtools'
  Requested charm-tools==2.0b1, but installing version 2.0-beta1
Downloading/unpacking launchpadlib (from charm-tools==2.0b1)
  Downloading launchpadlib-1.10.3.tar.gz (57kB): 57kB downloaded
  Running setup.py (path:/Users/jrwren/go/src/github.com/juju/charmstore-client/build/launchpadlib/setup.py) egg_info for package launchpadlib

Downloading/unpacking argparse (from charm-tools==2.0b1)
  Downloading argparse-1.4.0-py2.py3-none-any.whl
Downloading/unpacking cheetah (from charm-tools==2.0b1)
  Downloading Cheetah-2.4.4.tar.gz (190kB): 190kB downloaded
  Running setup.py (path:/Users/jrwren/go/src/github.com/juju/charmstore-client/build/cheetah/setup.py) egg_info for package cheetah
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/Users/jrwren/go/src/github.com/juju/charmstore-client/build/cheetah/setup.py", line 10, in <module>
        import SetupTools
      File "/Users/jrwren/go/src/github.com/juju/charmstore-client/build/cheetah/SetupTools.py", line 50
        except DistutilsPlatformError, x:
                                     ^
    SyntaxError: invalid syntax
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/Users/jrwren/go/src/github.com/juju/charmstore-client/build/cheetah/setup.py", line 10, in <module>

    import SetupTools

  File "/Users/jrwren/go/src/github.com/juju/charmstore-client/build/cheetah/SetupTools.py", line 50

    except DistutilsPlatformError, x:

                                 ^

SyntaxError: invalid syntax

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /Users/jrwren/go/src/github.com/juju/charmstore-client/build/cheetah
Storing debug log for failure in /Users/jrwren/.pip/pip.log
```

Looks like a dependency, cheetah, is not python 3 compatible.

**Comment by cholcombe973** [comment]
I just hit the same issue on xenial

**Comment by marcoceppi** [comment]
This was because we did not have a good enough Python in precise. But given
we're dropping support and moving to snaps I'll move this project to py3
(and help shake out any deps)
