### ISSUE TITLE
NameError: global name 'actions_yaml_file' is not defined

### ISSUE THREAD

**Issue by ryan-beisner** [juju/charm-tools#167]
The latest charm tools is broken, and has in turn broken the gate for OpenStack charm testing and code landing upstream.  Please consider an urgent revert or fix.  Thank you.

```
INFO:root:Workspace dir: /var/lib/jenkins/workspace/test_charm_lint
INFO:root:Reading file: Makefile
INFO:root:Searching for: ['@flake8', '/flake8', 'tox -e pep8']
INFO:root:command:  make -f Makefile lint
pep8 create: /var/lib/jenkins/checkout/cinder/.tox/pep8
pep8 installdeps: -r/var/lib/jenkins/checkout/cinder/requirements.txt, -r/var/lib/jenkins/checkout/cinder/test-requirements.txt
pep8 runtests: commands[0] | flake8 hooks unit_tests tests actions
pep8 runtests: commands[1] | charm-proof
Traceback (most recent call last):
  File ".tox/pep8/bin/charm-proof", line 9, in <module>
    load_entry_point('charm-tools==2.1.0', 'console_scripts', 'charm-proof')()
  File "/var/lib/jenkins/checkout/cinder/.tox/pep8/local/lib/python2.7/site-packages/charmtools/proof.py", line 62, in main
    lint, exit_code = proof(args_.charm_name, args_.bundle, args_.debug)
  File "/var/lib/jenkins/checkout/cinder/.tox/pep8/local/lib/python2.7/site-packages/charmtools/proof.py", line 56, in proof
    lint, err_code = c.proof()
  File "/var/lib/jenkins/checkout/cinder/.tox/pep8/local/lib/python2.7/site-packages/charmtools/charms.py", line 416, in proof
    if os.path.exists(actions_yaml_file):
NameError: global name 'actions_yaml_file' is not defined
ERROR: InvocationError: '/var/lib/jenkins/checkout/cinder/.tox/pep8/bin/charm-proof'
___________________________________ summary ____________________________________
ERROR:   pep8: commands failed
make: *** [lint] Error 1
ERROR:root:Make target returned non-zero.
```

**Comment by ryan-beisner** [comment]
https://github.com/juju/charm-tools/blame/d38986c79977abf41b505106964d7d1fb468208c/charmtools/charms.py#L415

**Comment by ryan-beisner** [comment]
https://github.com/juju/charm-tools/commit/9175edcdaae825192b784569aa1f33e46db15c93
