### ISSUE TITLE
charm build should have better error message

### ISSUE THREAD

**Issue by mbruzek** [juju/charm-tools#176]
I was doing a charm build and got an error message:

```
build: Processing layer: layer:docker
build: Processing layer: layer:basic
Traceback (most recent call last):
  File "/usr/bin/charm-build", line 9, in <module>
    load_entry_point('charm-tools==2.1.2', 'console_scripts', 'charm-build')()
  File "/usr/lib/python2.7/dist-packages/charmtools/build/__init__.py", line 673, in main
    build()
  File "/usr/lib/python2.7/dist-packages/charmtools/build/__init__.py", line 516, in __call__
    self.generate()
  File "/usr/lib/python2.7/dist-packages/charmtools/build/__init__.py", line 467, in generate
    self.formulate_plan(layers)
  File "/usr/lib/python2.7/dist-packages/charmtools/build/__init__.py", line 408, in formulate_plan
    self.plan = self.plan_layers(layers, output_files)
  File "/usr/lib/python2.7/dist-packages/charmtools/build/__init__.py", line 324, in plan_layers
    output_files=output_files))
  File "/usr/lib/python2.7/dist-packages/charmtools/build/__init__.py", line 320, in <genexpr>
    list(e for e in utils.walk(layer.directory,
  File "/usr/lib/python2.7/dist-packages/charmtools/utils.py", line 348, in walk
    yield (entry, fn(entry, **kwargs))
  File "/usr/lib/python2.7/dist-packages/charmtools/build/__init__.py", line 296, in build_tactics
    tactic = current.combine(existing)
  File "/usr/lib/python2.7/dist-packages/charmtools/build/tactics.py", line 470, in combine
    super(MetadataYAML, self).combine(existing)
  File "/usr/lib/python2.7/dist-packages/charmtools/build/tactics.py", line 285, in combine
    existing.read()
  File "/usr/lib/python2.7/dist-packages/charmtools/build/tactics.py", line 465, in read
    super(MetadataYAML, self).read()
  File "/usr/lib/python2.7/dist-packages/charmtools/build/tactics.py", line 280, in read
    self.data = self.load(self.entity.open()) or {}
  File "/usr/lib/python2.7/dist-packages/charmtools/build/tactics.py", line 323, in load
    return yaml.load(fn, Loader=yaml.RoundTripLoader)
  File "/usr/local/lib/python2.7/dist-packages/ruamel/yaml/main.py", line 75, in load
    return loader.get_single_data()
  File "/usr/local/lib/python2.7/dist-packages/ruamel/yaml/constructor.py", line 59, in get_single_data
    node = self.get_single_node()
  File "/usr/local/lib/python2.7/dist-packages/ruamel/yaml/composer.py", line 48, in get_single_node
    document = self.compose_document()
  File "/usr/local/lib/python2.7/dist-packages/ruamel/yaml/composer.py", line 68, in compose_document
    node = self.compose_node(None, None)
  File "/usr/local/lib/python2.7/dist-packages/ruamel/yaml/composer.py", line 99, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/local/lib/python2.7/dist-packages/ruamel/yaml/composer.py", line 158, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/usr/local/lib/python2.7/dist-packages/ruamel/yaml/composer.py", line 99, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/local/lib/python2.7/dist-packages/ruamel/yaml/composer.py", line 158, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/usr/local/lib/python2.7/dist-packages/ruamel/yaml/composer.py", line 99, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/local/lib/python2.7/dist-packages/ruamel/yaml/composer.py", line 158, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/usr/local/lib/python2.7/dist-packages/ruamel/yaml/composer.py", line 77, in compose_node
    if self.check_event(AliasEvent):
  File "/usr/local/lib/python2.7/dist-packages/ruamel/yaml/parser_.py", line 120, in check_event
    self.current_event = self.state()
  File "/usr/local/lib/python2.7/dist-packages/ruamel/yaml/parser_.py", line 520, in parse_block_mapping_value
    token = self.get_token()
  File "/usr/local/lib/python2.7/dist-packages/ruamel/yaml/scanner.py", line 1577, in get_token
    while self.need_more_tokens():
  File "/usr/local/lib/python2.7/dist-packages/ruamel/yaml/scanner.py", line 165, in need_more_tokens
    self.stale_possible_simple_keys()
  File "/usr/local/lib/python2.7/dist-packages/ruamel/yaml/scanner.py", line 309, in stale_possible_simple_keys
    "could not find expected ':'", self.get_mark())
ruamel.yaml.scanner.ScannerError: while scanning a simple key
  in "/home/mbruzek/workspace/layers/docker/metadata.yaml", line 21, column 1
could not find expected ':'
  in "/home/mbruzek/workspace/layers/docker/metadata.yaml", line 22, column 12
```

When I checked the current layer's metadata.yaml file I was not able to find the problem. It was in the .../layers/docker/metadata.yaml file.

We could make a better error message here, and maybe I should be the one to work on that.

**Comment by mbruzek** [comment]
The error was due to a merge failure.

```yaml
storage:
  disk-pool:
    type: block
    multiple:
<<<<<<< HEAD
      range: 0-
=======
      range: 0-10
    
>>>>>>> 924f4749f8644a16cebc5904e0718c85a54c4d5c
```

**Comment by marcoceppi** [comment]
This message was due to a failure to parse yaml. We should catch `ruamel.yaml.scanner.ScannerError` and simply reply back with `Failed to process FILE, not valid YAML`
