### ISSUE TITLE
charm build fails after upgrade to 1.11.2

### ISSUE THREAD

**Issue by SaMnCo** [juju/charm-tools#180]
Hi there, 

This morning I had a very unpleasant surprise: 

```
$ charm build
Traceback (most recent call last):
  File "/usr/bin/charm-build", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3141, in <module>
    @_call_aside
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3127, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3154, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 640, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 941, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 828, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'path.py' distribution was not found and is required by charm-tools
```

I didn't do anything more than ```apt-get update && apt-get upgrade -yqq``` on my desktop, which resulted in upgrading charm tools to 1.11.2. 

```
$ uname -a
Linux b8l2h92 4.2.0-34-generic #39-Ubuntu SMP Thu Mar 10 22:13:01 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 15.10
Release:	15.10
Codename:	wily
```

The exact same build worked yesterday and still works on my 1.11.1 from the laptop.

**Comment by SaMnCo** [comment]
Trying to fix, but this seems to be completely broken: 

```
$ sudo apt-get install python-path python3-path
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  python-path python3-path
0 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
Need to get 49,6 kB of archives.
After this operation, 229 kB of additional disk space will be used.
Get:1 http://ppa.launchpad.net/juju/stable/ubuntu/ wily/main python-path all 8.1.2+dfsg-1ubuntu1~ubuntu15.10.1~ppa1 [24,7 kB]
Get:2 http://ppa.launchpad.net/juju/stable/ubuntu/ wily/main python3-path all 8.1.2+dfsg-1ubuntu1~ubuntu15.10.1~ppa1 [24,8 kB]
Fetched 49,6 kB in 0s (214 kB/s)        
Selecting previously unselected package python-path.
(Reading database ... 384289 files and directories currently installed.)
Preparing to unpack .../python-path_8.1.2+dfsg-1ubuntu1~ubuntu15.10.1~ppa1_all.deb ...
Unpacking python-path (8.1.2+dfsg-1ubuntu1~ubuntu15.10.1~ppa1) ...
Selecting previously unselected package python3-path.
Preparing to unpack .../python3-path_8.1.2+dfsg-1ubuntu1~ubuntu15.10.1~ppa1_all.deb ...
Unpacking python3-path (8.1.2+dfsg-1ubuntu1~ubuntu15.10.1~ppa1) ...
Setting up python-path (8.1.2+dfsg-1ubuntu1~ubuntu15.10.1~ppa1) ...
Setting up python3-path (8.1.2+dfsg-1ubuntu1~ubuntu15.10.1~ppa1) ...
$ charm build
Traceback (most recent call last):
  File "/usr/bin/charm-build", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3141, in <module>
    @_call_aside
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3127, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3154, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 640, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 941, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 828, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'otherstuf' distribution was not found and is required by charm-tools
$ sudo apt-get install python-otherstuf
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following extra packages will be installed:
  python-stuf
The following NEW packages will be installed:
  python-otherstuf python-stuf
0 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/23,3 kB of archives.
After this operation, 119 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
Selecting previously unselected package python-stuf.
(Reading database ... 384309 files and directories currently installed.)
Preparing to unpack .../python-stuf_0.9.16-1ubuntu3~ubuntu15.10.1~ppa1_all.deb ...
Unpacking python-stuf (0.9.16-1ubuntu3~ubuntu15.10.1~ppa1) ...
Selecting previously unselected package python-otherstuf.
Preparing to unpack .../python-otherstuf_1.1.0-1ubuntu2~ubuntu15.10.1~ppa1_all.deb ...
Unpacking python-otherstuf (1.1.0-1ubuntu2~ubuntu15.10.1~ppa1) ...
Setting up python-stuf (0.9.16-1ubuntu3~ubuntu15.10.1~ppa1) ...
Setting up python-otherstuf (1.1.0-1ubuntu2~ubuntu15.10.1~ppa1) ...
$ charm build
Traceback (most recent call last):
  File "/usr/bin/charm-build", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3141, in <module>
    @_call_aside
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3127, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3154, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 640, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 941, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 828, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pathspec' distribution was not found and is required by charm-tools
$ sudo apt-get install python-pathspec
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  python-pathspec
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/12,8 kB of archives.
After this operation, 64,5 kB of additional disk space will be used.
Selecting previously unselected package python-pathspec.
(Reading database ... 384347 files and directories currently installed.)
Preparing to unpack .../python-pathspec_0.3.4-1ubuntu1~ubuntu15.10.1~ppa1_all.deb ...
Unpacking python-pathspec (0.3.4-1ubuntu1~ubuntu15.10.1~ppa1) ...
Setting up python-pathspec (0.3.4-1ubuntu1~ubuntu15.10.1~ppa1) ...
$ charm build
Traceback (most recent call last):
  File "/usr/bin/charm-build", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3141, in <module>
    @_call_aside
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3127, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3154, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 640, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 941, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 828, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'ruamel.yaml' distribution was not found and is required by charm-tools
$ 
```

**Comment by SaMnCo** [comment]
At last...

```
$ sudo apt-get install python-ruamel.yaml
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following extra packages will be installed:
  python-ruamel.base python-ruamel.ordereddict python-ruamel.std.argparse
The following NEW packages will be installed:
  python-ruamel.base python-ruamel.ordereddict python-ruamel.std.argparse python-ruamel.yaml
0 upgraded, 4 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/97,0 kB of archives.
After this operation, 569 kB of additional disk space will be used.
Do you want to continue? [Y/n] Y
Selecting previously unselected package python-ruamel.base.
(Reading database ... 384367 files and directories currently installed.)
Preparing to unpack .../python-ruamel.base_1.0.0-1ubuntu2~ubuntu15.10.1~ppa1_all.deb ...
Unpacking python-ruamel.base (1.0.0-1ubuntu2~ubuntu15.10.1~ppa1) ...
Selecting previously unselected package python-ruamel.ordereddict:amd64.
Preparing to unpack .../python-ruamel.ordereddict_0.4.9-1ubuntu2~ubuntu15.10.1~ppa1_amd64.deb ...
Unpacking python-ruamel.ordereddict:amd64 (0.4.9-1ubuntu2~ubuntu15.10.1~ppa1) ...
Selecting previously unselected package python-ruamel.std.argparse.
Preparing to unpack .../python-ruamel.std.argparse_0.6.0-1ubuntu2~ubuntu15.10.1~ppa1_all.deb ...
Unpacking python-ruamel.std.argparse (0.6.0-1ubuntu2~ubuntu15.10.1~ppa1) ...
Selecting previously unselected package python-ruamel.yaml.
Preparing to unpack .../python-ruamel.yaml_0.10.2-1ubuntu2~ubuntu15.10.1~ppa1_amd64.deb ...
Unpacking python-ruamel.yaml (0.10.2-1ubuntu2~ubuntu15.10.1~ppa1) ...
Setting up python-ruamel.base (1.0.0-1ubuntu2~ubuntu15.10.1~ppa1) ...
Setting up python-ruamel.ordereddict:amd64 (0.4.9-1ubuntu2~ubuntu15.10.1~ppa1) ...
Error processing line 2 of /usr/lib/python2.7/dist-packages/ruamel.std.argparse-0.6.0-nspkg.pth:

  Traceback (most recent call last):
    File "/usr/lib/python2.7/site.py", line 158, in addpackage
      exec line
    File "<string>", line 1, in <module>
  KeyError: 'ruamel'

Remainder of file ignored
Setting up python-ruamel.std.argparse (0.6.0-1ubuntu2~ubuntu15.10.1~ppa1) ...
Error processing line 2 of /usr/lib/python2.7/dist-packages/ruamel.std.argparse-0.6.0-nspkg.pth:

  Traceback (most recent call last):
    File "/usr/lib/python2.7/site.py", line 158, in addpackage
      exec line
    File "<string>", line 1, in <module>
  KeyError: 'ruamel'

Remainder of file ignored
Setting up python-ruamel.yaml (0.10.2-1ubuntu2~ubuntu15.10.1~ppa1) ...
$ charm build
build: Composing into /home/scozannet/Documents/src/juju/charms
build: Destination charm directory: /home/scozannet/Documents/src/juju/charms/trusty/deeplearning4j
build: Please add a `repo` key to your layer.yaml, e.g. repo: git@github.com:SaMnCo/layer-nvidia-docker.git
build: Processing layer: layer:basic
build: Processing layer: layer:apt
build: Processing layer: layer:cuda
build: Processing layer: deeplearning4j
```

**Comment by marcoceppi** [comment]
You should be on 2.1.2 at this point. the missing packages is a [known issue](https://bugs.launchpad.net/ubuntu/+source/charm-tools/+bug/1569531) and has been patched. You should see an update to wily from the ppa:juju/stable in an hour. Xenial is already fix released
