### ISSUE TITLE
virtualenv error in Xenial on Power

### ISSUE THREAD

**Issue by SaMnCo** [juju/charm-tools#181]
Hi there, 

On a Power8 architecture (IBM S824L) on Xenial: 

```
# for CHARM in deeplearning4j cuda
> do
> cd "${LAYER_PATH}/${CHARM}"
> charm build
> done
build: Composing into /root/charms
build: Destination charm directory: /root/charms/trusty/deeplearning4j
build: Please add a `repo` key to your layer.yaml, e.g. repo: https://github.com/SaMnCo/layer-skymind-dl4j.git
build: Processing layer: layer:basic
build: Processing layer: layer:cuda
build: Processing layer: deeplearning4j
Already using interpreter /usr/bin/python3
Using base prefix '/usr'
New python executable in /tmp/tmpWFkunW/bin/python3
Also creating executable in /tmp/tmpWFkunW/bin/python
Installing setuptools, pkg_resources, _markerlib, pip, wheel...
  Complete output from command /tmp/tmpWFkunW/bin/python3 - setuptools pkg_resources _markerlib pip wheel:
  Traceback (most recent call last):
  File "<stdin>", line 24, in <module>
  File "/usr/share/python-wheels/pip-8.1.1-py2.py3-none-any.whl/pip/__init__.py", line 215, in main
  File "/tmp/tmpWFkunW/lib/python3.5/locale.py", line 595, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
----------------------------------------
...Installing setuptools, pkg_resources, _markerlib, pip, wheel...done.
Traceback (most recent call last):
  File "/usr/bin/virtualenv", line 9, in <module>
    load_entry_point('virtualenv==15.0.1', 'console_scripts', 'virtualenv')()
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 719, in main
    symlink=options.symlink)
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 989, in create_environment
    download=download,
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 918, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT)
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 812, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /tmp/tmpWFkunW/bin/python3 - setuptools pkg_resources _markerlib pip wheel failed with error code 1

Command failed: virtualenv --python python3 /tmp/tmpWFkunW
build: Composing into /root/charms
build: Destination charm directory: /root/charms/trusty/cuda
build: Please add a `repo` key to your layer.yaml, e.g. repo: https://github.com/SaMnCo/layer-nvidia-cuda.git
build: Processing layer: layer:basic
build: Processing layer: cuda
Already using interpreter /usr/bin/python3
Using base prefix '/usr'
New python executable in /tmp/tmpafxAJu/bin/python3
Also creating executable in /tmp/tmpafxAJu/bin/python
Installing setuptools, pkg_resources, _markerlib, pip, wheel...
  Complete output from command /tmp/tmpafxAJu/bin/python3 - setuptools pkg_resources _markerlib pip wheel:
  Traceback (most recent call last):
  File "<stdin>", line 24, in <module>
  File "/usr/share/python-wheels/pip-8.1.1-py2.py3-none-any.whl/pip/__init__.py", line 215, in main
  File "/tmp/tmpafxAJu/lib/python3.5/locale.py", line 595, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
----------------------------------------
...Installing setuptools, pkg_resources, _markerlib, pip, wheel...done.
Traceback (most recent call last):
  File "/usr/bin/virtualenv", line 9, in <module>
    load_entry_point('virtualenv==15.0.1', 'console_scripts', 'virtualenv')()
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 719, in main
    symlink=options.symlink)
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 989, in create_environment
    download=download,
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 918, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT)
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 812, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /tmp/tmpafxAJu/bin/python3 - setuptools pkg_resources _markerlib pip wheel failed with error code 1

Command failed: virtualenv --python python3 /tmp/tmpafxAJu
```

Will dig into this...

**Comment by SaMnCo** [comment]
OK apparently python3 is VERY sensitive to locales problems:

```
root@deepsummit:~/charms/layers/cuda# export LC_ALL="en_US.UTF-8"
root@deepsummit:~/charms/layers/cuda# export LC_CTYPE="en_US.UTF-8"
root@deepsummit:~/charms/layers/cuda# sudo dpkg-reconfigure locales
Generating locales (this might take a while)...
  en_US.ISO-8859-1... done
  en_US.UTF-8... done
Generation complete.
root@deepsummit:~/charms/layers/cuda# cd ~
root@deepsummit:~# for CHARM in deeplearning4j cuda; do cd "${LAYER_PATH}/${CHARM}"; charm build; done
build: Composing into /root/charms
build: Destination charm directory: /root/charms/trusty/deeplearning4j
build: Please add a `repo` key to your layer.yaml, e.g. repo: https://github.com/SaMnCo/layer-skymind-dl4j.git
build: Processing layer: layer:basic
build: Processing layer: layer:cuda
build: Processing layer: deeplearning4j
build: Composing into /root/charms
build: Destination charm directory: /root/charms/trusty/cuda
build: Please add a `repo` key to your layer.yaml, e.g. repo: https://github.com/SaMnCo/layer-nvidia-cuda.git
build: Processing layer: layer:basic
build: Processing layer: cuda

```

**Comment by marcoceppi** [comment]
This might be worth documenting somewhere. I'm sure others will hit this
problem
