### ISSUE TITLE
failure to detect type change during build

### ISSUE THREAD

**Issue by marcoceppi** [juju/charm-tools#183]
If you have an invalid file, during YAMLTactic, in deepmerge, everything will explode spectacularly.

```
Traceback (most recent call last):
  File "/usr/bin/charm-build", line 9, in <module>
    load_entry_point('charm-tools==2.1.2', 'console_scripts', 'charm-build')()
  File "/usr/lib/python2.7/dist-packages/charmtools/build/__init__.py", line 673, in main
    build()
  File "/usr/lib/python2.7/dist-packages/charmtools/build/__init__.py", line 516, in __call__
    self.generate()
  File "/usr/lib/python2.7/dist-packages/charmtools/build/__init__.py", line 467, in generate
    self.formulate_plan(layers)
  File "/usr/lib/python2.7/dist-packages/charmtools/build/__init__.py", line 408, in formulate_plan
    self.plan = self.plan_layers(layers, output_files)
  File "/usr/lib/python2.7/dist-packages/charmtools/build/__init__.py", line 324, in plan_layers
    output_files=output_files))
  File "/usr/lib/python2.7/dist-packages/charmtools/build/__init__.py", line 320, in <genexpr>
    list(e for e in utils.walk(layer.directory,
  File "/usr/lib/python2.7/dist-packages/charmtools/utils.py", line 348, in walk
    yield (entry, fn(entry, **kwargs))
  File "/usr/lib/python2.7/dist-packages/charmtools/build/__init__.py", line 296, in build_tactics
    tactic = current.combine(existing)
  File "/usr/lib/python2.7/dist-packages/charmtools/build/tactics.py", line 288, in combine
    self.data = utils.deepmerge(existing.data, self.data)
  File "/usr/lib/python2.7/dist-packages/charmtools/utils.py", line 55, in deepmerge
    deepmerge(dest[k], v)
  File "/usr/lib/python2.7/dist-packages/charmtools/utils.py", line 55, in deepmerge
    deepmerge(dest[k], v)
  File "/usr/lib/python2.7/dist-packages/charmtools/utils.py", line 54, in deepmerge
    if dest.get(k) and isinstance(v, dict):
AttributeError: 'PreservedScalarString' object has no attribute 'get'
```

This was caused because `layer:apt` has the following:

```yaml
  install_keys:
    description: >
        List of signing keys for install_sources package sources, per
        charmhelpers standard format (a yaml list of strings encoded as
        a string). The keys should be the full ASCII armoured GPG public
        keys. While GPG key ids are also supported and looked up on a
        keyserver, operators should be aware that this mechanism is
        insecure. null can be used if a standard package signing key is
        used that will already be installed on the machine, and for PPA
        sources where the package signing key is securely retrieved from
        Launchpad.
    type: string
    default: ""
```

and `layer:puppet` has the following

```yaml
options:
  install_sources: |
    - http://apt.puppetlabs.com trusty main
    - http://apt.puppetlabs.com trusty dependencies
  install_keys: |
      - '4BD6EC30'
      - '4BD6EC30'
```

Since a dictionary was trying to be merged with a string the resulting error blew up. We need to better detect these formatting issues and give users actionable output instead of razor-blades to the eyes.

**Comment by marcoceppi** [comment]
I've considered running `charm proof` against the layer, which does not help much in diagnosis since there are a lot of expected failures:

```
E: Charm must have either a maintainer or maintainers field
W: Metadata missing required field "tags"
I: No icon.svg file.
I: no hooks directory
I: all charms should provide at least one thing
I: missing recommended hook install
I: missing recommended hook start
I: missing recommended hook stop
I: missing recommended hook config-changed
E: config.yaml: data for option install_keys is not a dict
E: config.yaml: data for option install_sources is not a dict
```

However, we may wish to adopt a few choice charm lints, such as the `config.yaml` this also has drawbacks, because the next level is

```
W: config.yaml: option install_keys does not have the keys: description, type
W: config.yaml: option install_sources does not have the keys: description, type
```
