### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'items'

### ISSUE THREAD

**Issue by cholcombe973** [juju/charm-tools#225]
## Checklist

 - [X] Confirmed this is an issue with charm-tools, not charmstore-client
 - [X] Provide versions of tools used
 - [X] Described the feature or ways to replicate the issue

## What version am I running?

I ran the following command: `charm version` and got the following output:

```
charm-tools 1.11.0
```

I am using: 3.16.0-52-generic #71~14.04.1-Ubuntu SMP Fri Oct 23 17:24:53 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

### I expect/expected the following

charm build should've built the layered charm I'm working on.

### What I got

I'm not entirely sure how I ended up getting it to do this but:
```
build: Composing into /home/ubuntu/charms
build: Processing layer: layer:basic
build: Processing layer: layer:apt
build: Processing layer: layer:ceph-base
build: Processing layer: charm-ceph-fs
Traceback (most recent call last):
  File "/usr/bin/charm-build", line 9, in <module>
    load_entry_point('charm-tools==1.11.0', 'console_scripts', 'charm-build')()
  File "/usr/lib/python2.7/dist-packages/charmtools/build/__init__.py", line 563, in main
    build()
  File "/usr/lib/python2.7/dist-packages/charmtools/build/__init__.py", line 460, in __call__
    self.generate()
  File "/usr/lib/python2.7/dist-packages/charmtools/build/__init__.py", line 424, in generate
    self.formulate_plan(layers)
  File "/usr/lib/python2.7/dist-packages/charmtools/build/__init__.py", line 374, in formulate_plan
    self.plan_interfaces(layers, output_files, self.plan)
  File "/usr/lib/python2.7/dist-packages/charmtools/build/__init__.py", line 317, in plan_interfaces
    for k, v in meta.get(kind, {}).items():
AttributeError: 'NoneType' object has no attribute 'items'
```
I'm guessing that items is being called on a variable before checking if the object has the attribute. Should be an easy one liner fix.  I'd be happy to PR this if you'd like.

The problem occurred after I added my new interface I'm working on into the layer.yaml file. Deleting the built charm directory does not resolve the issue.  

Commenting out the metadata.yaml requires,provides sections seems to solve it.  I'm guessing there's a mismatch in there of what I'm asking for and what is available.

**Comment by marcoceppi** [comment]
2.1.2 is the latest charm tools, please upgrade first.
