### ISSUE TITLE
Latest PPA release is broken on trusty

### ISSUE THREAD

**Issue by AdamIsrael** [juju/charm-tools#274]
Ubuntu 14.04 ships with pip 1.5.4-1, while the latest charm-tools released in the juju/stable ppa requires 7.1.2 in order to build a charm. 

```
charm build -s xenial -obuild src
Traceback (most recent call last):
  File "/usr/bin/charm-build", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2927, in <module>
    @_call_aside
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2913, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2940, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 637, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 650, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 829, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pip>=7.1.2' distribution was not found and is required by charm-tools
```
Complte build log: https://build.opnfv.org/ci/view/joid/job/joid-deploy-baremetal-daily-colorado/502/console

**Comment by bloodearnest** [comment]
Hey folks

This is blocking our build pipelines at the minute, any thing we can do to help fix?

**Comment by johnsca** [comment]
Combined with #276, do we even have a functioning charm-build at this point?

**Comment by marcoceppi** [comment]
2.1.6 is built and addresses this issue
