### ISSUE TITLE
Snap charm create failing

### ISSUE THREAD

**Issue by geekgonecrazy** [juju/charm-tools#287]
## Checklist

 - [X] Confirmed this is an issue with charm-tools, not charmstore-client
 - [X] Provide versions of tools used
 - [X] Described the feature or ways to replicate the issue

## What version am I running?

I ran the following command: `charm version` and got the following ouput:

```
charm 2.2.0
charm-tools 2.1.8
```

Snap Version:

```
Name               Version  Rev  Developer  Notes
charm              2.2      9    charms
```

I am using: Ubuntu 16.04.1 LTS

## Issue/Feature

`charm create -t bash my-charm` command throwing an error

### I expect/expected the following

to bootstrap charm so I could start development

### What I got

Ran: `charm create -t bash my-charm`
Output:
```
Traceback (most recent call last):
  File "/snap/charm/9/bin/charm-create", line 11, in <module>
    sys.exit(main())
  File "/snap/charm/9/lib/python2.7/site-packages/charmtools/create.py", line 96, in main
    generator = CharmGenerator(args)
  File "/snap/charm/9/lib/python2.7/site-packages/charmtools/generators/generator.py", line 44, in __init__
    self.plugin = self._load_plugin()
  File "/snap/charm/9/lib/python2.7/site-packages/charmtools/generators/generator.py", line 53, in _load_plugin
    return ep.load()()
  File "/snap/charm/9/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2290, in load
    self.require(*args, **kwargs)
  File "/snap/charm/9/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2307, in require
    items = working_set.resolve(reqs, env, installer)
  File "/snap/charm/9/lib/python2.7/site-packages/pkg_resources/__init__.py", line 858, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (SecretStorage 2.3.1 (/snap/charm/9/lib/python2.7/site-packages), Requirement.parse('secretstorage<2.3.0'))
```

Tried specifying folder got the same output.

**Comment by jameinel** [comment]
Confirmed that this is happening for me as well. The 'snap' seems to be providing a version of SecreteStorage that is newer than the charm says it is going to work with.

**Comment by jameinel** [comment]
Note that if I switch to the "--beta" channel, which actually has an older version, it then "charm create" works.

Specifically:
  snap refresh charm --beta
Says that it installs version "7" of the snap, which has:
$ charm version
charm 2.2.0
charm-tools 2.1.5

And "charm create" ends up with a reactive based charm.

**Comment by mitechie** [comment]
The 2.2 version is pushed through all channels so there is no longer a path around the dep issue.
