### ISSUE TITLE
Permission denied: '/etc' with charm snap

### ISSUE THREAD

**Issue by elopio** [juju/charm-tools#288]
## Checklist

 - [X] Confirmed this is an issue with charm-tools, not charmstore-client
 - [X] Provide versions of tools used:
 - [X] Described the feature or ways to replicate the issue

I am using: ubuntu xenial

```
$ charm version
charm 2.2.0
charm-tools 2.1.8
$ snap list charm
Name   Version  Rev  Developer  Notes
charm  2.2      9    charms     -
```

### I expect/expected the following

I expected charm build to work.
 
### What I got

$ charm build
build: Composing into /home/elopio/workspace/remote-comms
build: Destination charm directory: /home/elopio/workspace/remote-comms/builds/remote-comms
build: Processing layer: layer:basic
build: Processing layer: remote-comms
Exception:
Traceback (most recent call last):
  File "/tmp/tmpQ1srIU/lib/python3.5/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/tmp/tmpQ1srIU/lib/python3.5/site-packages/pip/commands/install.py", line 272, in run
    with self._build_session(options) as session:
  File "/tmp/tmpQ1srIU/lib/python3.5/site-packages/pip/basecommand.py", line 72, in _build_session
    insecure_hosts=options.trusted_hosts,
  File "/tmp/tmpQ1srIU/lib/python3.5/site-packages/pip/download.py", line 329, in __init__
    self.headers["User-Agent"] = user_agent()
  File "/tmp/tmpQ1srIU/lib/python3.5/site-packages/pip/download.py", line 93, in user_agent
    from pip._vendor import distro
  File "/tmp/tmpQ1srIU/lib/python3.5/site-packages/pip/_vendor/distro.py", line 1050, in <module>
    _distro = LinuxDistribution()
  File "/tmp/tmpQ1srIU/lib/python3.5/site-packages/pip/_vendor/distro.py", line 595, in __init__
    self._distro_release_info = self._get_distro_release_info()
  File "/tmp/tmpQ1srIU/lib/python3.5/site-packages/pip/_vendor/distro.py", line 984, in _get_distro_release_info
    basenames = os.listdir(_UNIXCONFDIR)
PermissionError: [Errno 13] Permission denied: '/etc'
Traceback (most recent call last):
  File "/tmp/tmpQ1srIU/bin/pip3", line 11, in <module>
    sys.exit(main())
  File "/tmp/tmpQ1srIU/lib/python3.5/site-packages/pip/__init__.py", line 233, in main
    return command.main(cmd_args)
  File "/tmp/tmpQ1srIU/lib/python3.5/site-packages/pip/basecommand.py", line 251, in main
    timeout=min(5, options.timeout)) as session:
  File "/tmp/tmpQ1srIU/lib/python3.5/site-packages/pip/basecommand.py", line 72, in _build_session
    insecure_hosts=options.trusted_hosts,
  File "/tmp/tmpQ1srIU/lib/python3.5/site-packages/pip/download.py", line 329, in __init__
    self.headers["User-Agent"] = user_agent()
  File "/tmp/tmpQ1srIU/lib/python3.5/site-packages/pip/download.py", line 93, in user_agent
    from pip._vendor import distro
  File "/tmp/tmpQ1srIU/lib/python3.5/site-packages/pip/_vendor/distro.py", line 1050, in <module>
    _distro = LinuxDistribution()
  File "/tmp/tmpQ1srIU/lib/python3.5/site-packages/pip/_vendor/distro.py", line 595, in __init__
    self._distro_release_info = self._get_distro_release_info()
  File "/tmp/tmpQ1srIU/lib/python3.5/site-packages/pip/_vendor/distro.py", line 984, in _get_distro_release_info
    basenames = os.listdir(_UNIXCONFDIR)
PermissionError: [Errno 13] Permission denied: '/etc'

Command failed: bash -c . /tmp/tmpQ1srIU/bin/activate ; pip3 install -U "pip>=9.0.0,<10.0.0" "wheel>=0.29.0,<1.0.0"

**Comment by elopio** [comment]
Workaround: sudo apt install python3-pip

**Comment by marcoceppi** [comment]
Work around, how? Where? We've been trying to patch this issue for weeks

**Comment by elopio** [comment]
@marcoceppi no workaround, sorry, I was mistaken, so I deleted the comment. Apparently not fast enough :)

**Comment by marcoceppi** [comment]
This has been addressed in the snap
