### ISSUE TITLE
Empty .git dir copied into charms

### ISSUE THREAD

**Issue by gnuoy** [juju/charm-tools#289]
## Checklist

 - [X] Confirmed this is an issue with charm-tools, not charmstore-client
 - [x] Provide versions of tools used
 - [x] Described the feature or ways to replicate the issue

## What version am I running?

I ran the following command: `charm version` and got the following ouput:

```
> charm version
charm unavailable
charm-tools 2.1.8
```

I am using: Ubuntu Trusty

## Issue/Feature

When building a charm I get an empty .git directory. This tricks bundletester into thinking the charm is managed by git and bundletester raises an exception when it tries to recover the charm revision.

## To reproduce

git clone https://github.com/openstack/charm-tempest.git
cd charm-tempest
tox -e build
ls -l build/builds/tempest/.git
  total 0

**Comment by gnuoy** [comment]
Backing out this change: https://github.com/juju/charm-tools/pull/284/files fixes it for me

**Comment by ryan-beisner** [comment]
Here's the output of this in action:

```
DEBUG:runner:Exit Code: 0
DEBUG:deployer.env: Destroying application rabbitmq-server
DEBUG:deployer.env: Destroying application keystone
DEBUG:deployer.env: Destroying application percona-cluster
DEBUG:deployer.env: Destroying application openstack-dashboard
DEBUG:deployer.env: Destroying application glance
DEBUG:deployer.env: Destroying application tempest
DEBUG:deployer.env:  No unit errors found.
DEBUG:deployer.env: Terminating machines forcefully
DEBUG:deployer.env:  Terminating machine 19
DEBUG:deployer.env:  Terminating machine 20
DEBUG:deployer.env:  Terminating machine 21
DEBUG:deployer.env:  Terminating machine 22
DEBUG:deployer.env:  Terminating machine 23
DEBUG:deployer.env:  Terminating machine 24
INFO:deployer.env:  Waiting for machine termination
DEBUG:root:Waiting for applications to be removed...
DEBUG:runner:call ['/tmp/bundletester-SLQAPW/tempest/tests/gate-basic-xenial-newton'] (cwd: /tmp/bundletester-SLQAPW/tempest)
DEBUG:runner:2016-11-22 09:27:44,608 __init__ INFO: OpenStackAmuletDeployment:  init
DEBUG:runner:INFO:deployment-logger:OpenStackAmuletDeployment:  init
DEBUG:runner:2016-11-22 09:27:44,609 _add_services INFO: OpenStackAmuletDeployment:  adding services
DEBUG:runner:INFO:deployment-logger:OpenStackAmuletDeployment:  adding services
DEBUG:runner:2016-11-22 09:27:44,609 _determine_branch_locations INFO: OpenStackAmuletDeployment:  determine branch locations
DEBUG:runner:INFO:deployment-logger:OpenStackAmuletDeployment:  determine branch locations
DEBUG:runner:2016-11-22 09:27:48,830 _configure_services INFO: OpenStackAmuletDeployment:  configure services
DEBUG:runner:INFO:deployment-logger:OpenStackAmuletDeployment:  configure services
DEBUG:runner:2016-11-22 09:27:49 Starting deployment of osci-sv06
DEBUG:runner:2016-11-22 09:27:49 Deploying applications...
DEBUG:runner:2016-11-22 09:27:49  Deploying application glance using cs:~openstack-charmers-next/xenial/glance-258
DEBUG:runner:2016-11-22 09:27:53  Deploying application keystone using cs:~openstack-charmers-next/xenial/keystone-262
DEBUG:runner:2016-11-22 09:27:56  Deploying application openstack-dashboard using cs:~openstack-charmers-next/xenial/openstack-dashboard-247
DEBUG:runner:2016-11-22 09:28:00  Deploying application percona-cluster using cs:~openstack-charmers-next/xenial/percona-cluster-233
DEBUG:runner:2016-11-22 09:28:04  Deploying application rabbitmq-server using cs:~openstack-charmers-next/xenial/rabbitmq-server-244
DEBUG:runner:2016-11-22 09:28:08  Deploying application tempest using /tmp/charmcYictG/xenial/tempest
DEBUG:runner:2016-11-22 09:35:23 Adding relations...
DEBUG:runner:2016-11-22 09:35:23  Adding relation glance:shared-db <-> percona-cluster:shared-db
DEBUG:runner:2016-11-22 09:35:23  Adding relation keystone:shared-db <-> percona-cluster:shared-db
DEBUG:runner:2016-11-22 09:35:24  Adding relation tempest:dashboard <-> openstack-dashboard:website
DEBUG:runner:2016-11-22 09:35:24  Adding relation keystone:identity-admin <-> tempest:identity-admin
DEBUG:runner:2016-11-22 09:35:24  Adding relation glance:identity-service <-> keystone:identity-service
DEBUG:runner:2016-11-22 09:35:25  Adding relation openstack-dashboard:identity-service <-> keystone:identity-service
DEBUG:runner:2016-11-22 09:35:25  Adding relation glance:amqp <-> rabbitmq-server:amqp
DEBUG:runner:2016-11-22 09:36:26 Deployment complete in 517.13 seconds
DEBUG:runner:2016-11-22 09:38:46,304 __init__ INFO: Waiting on extended status checks...
DEBUG:runner:INFO:amulet-logger:Waiting on extended status checks...
DEBUG:runner:2016-11-22 09:38:46,305 _auto_wait_for_status INFO: Waiting for extended status on units...
DEBUG:runner:INFO:deployment-logger:Waiting for extended status on units...
DEBUG:runner:2016-11-22 09:38:46,305 _auto_wait_for_status DEBUG: Default extended status wait match:  contains READY (case-insensitive)
DEBUG:runner:DEBUG:deployment-logger:Default extended status wait match:  contains READY (case-insensitive)
DEBUG:runner:2016-11-22 09:38:46,308 _auto_wait_for_status DEBUG: Waiting up to 1800s for extended status on services: ['percona-cluster', 'rabbitmq-server', 'keystone', 'openstack-dashboard', 'glance', 'tempest']
DEBUG:runner:DEBUG:deployment-logger:Waiting up to 1800s for extended status on services: ['percona-cluster', 'rabbitmq-server', 'keystone', 'openstack-dashboard', 'glance', 'tempest']
DEBUG:runner:2016-11-22 09:38:46,579 _auto_wait_for_status INFO: OK
DEBUG:runner:INFO:deployment-logger:OK
DEBUG:runner:2016-11-22 09:38:46,866 _initialize_tests DEBUG: openstack release val: 5
DEBUG:runner:DEBUG:amulet-logger:openstack release val: 5
DEBUG:runner:2016-11-22 09:38:46,867 _initialize_tests DEBUG: openstack release str: newton
DEBUG:runner:DEBUG:amulet-logger:openstack release str: newton
DEBUG:runner:2016-11-22 09:38:46,867 test_run_tempest DEBUG: Running Tempest...
DEBUG:runner:DEBUG:amulet-logger:Running Tempest...
DEBUG:runner:Running command: juju action do --format=json tempest/4 run-tempest
DEBUG:runner:
DEBUG:runner:Exit Code: 0
DEBUG:bundletester.utils:Updating JUJU_ENV: "osci-sv06" -> ""
Traceback (most recent call last):
  File ".tox/func27/bin/bundletester", line 11, in <module>
    sys.exit(entrypoint())
  File "/var/lib/jenkins/workspace/test_charm_amulet_full/asset/tempest/.tox/func27/local/lib/python2.7/site-packages/bundletester/tester.py", line 152, in entrypoint
    status = main()
  File "/var/lib/jenkins/workspace/test_charm_amulet_full/asset/tempest/.tox/func27/local/lib/python2.7/site-packages/bundletester/tester.py", line 145, in main
    report.summary()
  File "/var/lib/jenkins/workspace/test_charm_amulet_full/asset/tempest/.tox/func27/local/lib/python2.7/site-packages/bundletester/reporter.py", line 163, in summary
    'revision': str(opts.fetcher.get_revision(opts.testdir)).strip(),
  File "/var/lib/jenkins/workspace/test_charm_amulet_full/asset/tempest/.tox/func27/local/lib/python2.7/site-packages/bundletester/fetchers.py", line 115, in get_revision
    return check_output('git rev-parse HEAD', cwd=dir_)
  File "/var/lib/jenkins/workspace/test_charm_amulet_full/asset/tempest/.tox/func27/local/lib/python2.7/site-packages/bundletester/fetchers.py", line 307, in check_output
    raise FetchError(out)
bundletester.fetchers.FetchError: fatal: Not a git repository (or any of the parent directories): .git

ERROR: InvocationError: '/var/lib/jenkins/workspace/test_charm_amulet_full/asset/tempest/.tox/func27/bin/bundletester -vl DEBUG -r json -o func-results.json --test-pattern gate-* --no-destroy'
```

**Comment by ryan-beisner** [comment]
For clarity, this is blocking OSCI from building/testing/publishing charms.
