### ISSUE TITLE
'charm build' of a new 'charm create' charm fails

### ISSUE THREAD

**Issue by jameinel** [juju/charm-tools#293]
I installed charm via "snap install charm", but I ran into issue #287, so I switched to '--beta' to create the charm. However "charm build" then failed, so I switched back to '--stable'. I now get:
$ charm version
charm 2.2.0
charm-tools 2.1.8

$ charm build                                                                                                        
build: Composing into /home/jameinel/dev/charms/ubuntu-lite                                                          
build: Destination charm directory: /home/jameinel/dev/charms/ubuntu-lite/trusty/ubuntu-lite                         
build: Please add a `repo` key to your layer.yaml, with a url from which your layer can be cloned.                   
build: Processing layer: layer:basic                                                                                 
build: Processing layer: ubuntu-lite                                                                                 
Exception:                                                                                                           
Traceback (most recent call last):                                                                                   
  File "/tmp/tmpc91NY3/lib/python3.5/site-packages/pip/basecommand.py", line 215, in main                            
    status = self.run(options, args)                                                                                 
  File "/tmp/tmpc91NY3/lib/python3.5/site-packages/pip/commands/install.py", line 272, in run                        
    with self._build_session(options) as session:                                                                    
  File "/tmp/tmpc91NY3/lib/python3.5/site-packages/pip/basecommand.py", line 72, in _build_session                   
    insecure_hosts=options.trusted_hosts,                                                                            
  File "/tmp/tmpc91NY3/lib/python3.5/site-packages/pip/download.py", line 329, in __init__                           
    self.headers["User-Agent"] = user_agent()                                                                        
  File "/tmp/tmpc91NY3/lib/python3.5/site-packages/pip/download.py", line 93, in user_agent                          
    from pip._vendor import distro                                                                                   
  File "/tmp/tmpc91NY3/lib/python3.5/site-packages/pip/_vendor/distro.py", line 1050, in <module>                    
    _distro = LinuxDistribution()                                                                                    
  File "/tmp/tmpc91NY3/lib/python3.5/site-packages/pip/_vendor/distro.py", line 595, in __init__                     
    self._distro_release_info = self._get_distro_release_info()                                                      
  File "/tmp/tmpc91NY3/lib/python3.5/site-packages/pip/_vendor/distro.py", line 984, in _get_distro_release_info     
    basenames = os.listdir(_UNIXCONFDIR)                                                                             
PermissionError: [Errno 13] Permission denied: '/etc'                                                                
Traceback (most recent call last):                                                                                     
...

There is more, but just the fact that it starts with "Permission denied: '/etc'". Do you have to install in --devmode?

**Comment by marcoceppi** [comment]
This is a known issue, the snap is still being worked on

**Comment by johnsca** [comment]
This has been resolved in the confined snap.
