### ISSUE TITLE
charm commands are not working due to ImportError

### ISSUE THREAD

**Issue by sebastienpattyn93** [juju/charm-tools#304]
## What version am I running?

I ran the following command: `charm version` and got the following ouput:
-> I was not even able to execute the `charm version ` command succesfully:

```
Traceback (most recent call last):
  File "/usr/bin/charm-version", line 9, in <module>
    load_entry_point('charm-tools==2.1.2', 'console_scripts', 'charm-version')()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 560, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2648, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2302, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2308, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/dist-packages/charmtools/__init__.py", line 23, in <module>
    from . import version
  File "/usr/lib/python2.7/dist-packages/charmtools/version.py", line 6, in <module>
    from charmtools import utils
  File "/usr/lib/python2.7/dist-packages/charmtools/utils.py", line 18, in <module>
    from path import path
ImportError: cannot import name path

```
I am not able to execute any charm command at the moment

**Comment by sebastienpattyn93** [comment]
I noticed that with the latest version of path.py, path needs to be imported like this : `from path import Path` instead of `from path import path` . I changed this in my charmtools/utils.py to `from path import Path as path` and now everything seems to work

**Comment by marcoceppi** [comment]
What version of charm-tools are you on? This should have been released and fixed recently.

**Comment by sebastienpattyn93** [comment]
I had it both with version 2.2.0 and with version 2.1.2. uninstalling path.py and installing a previous version of path.py, helped as well. I just keep having the issue with the latest release of path.py

**Comment by chuckbutler** [comment]
This is problematic and systemic. Path.py changed their import notation, and left a deprecation notice in the code-base for over a year at this point that they were deprecating the older notation. The proper fix would be to update charm-tools that uses path.py from:

```
from path import path
```
to
```
from path import Path
```

and if you really really want to avoid touching multiple lines to fix:

```
from path import Path as path
```

**Comment by galgalesh** [comment]
This has been fixed in master: https://github.com/juju/charm-tools/commit/f820f22e7f11287ff03d5528b1a6ece349c46afa

**Comment by johnsca** [comment]
This is no longer an issue with the confined snap.  Closing.
