### ISSUE TITLE
Cannot install on MacOS Sierra (10.12)

### ISSUE THREAD

**Issue by frankban** [juju/charm-tools#309]
Moved from https://github.com/CanonicalLtd/jujucharms.com/issues/400

Output of command "brew install charm-tools":

```
$ brew install charm-tools
Warning: You are using OS X 10.12.
We do not provide support for this pre-release version.
You may encounter build failures or other breakages.
Please create pull-requests instead of filing issues.
==> Installing dependencies for charm-tools: go, charm
==> Installing charm-tools dependency: go
==> Downloading https://storage.googleapis.com/golang/go1.6.3.src.tar.gz
Already downloaded: /Users/kkashalk/Library/Caches/Homebrew/go-1.6.3.tar.gz
==> Downloading https://storage.googleapis.com/golang/go1.4.2.darwin-amd64-osx10.8.tar.gz
Already downloaded: /Users/kkashalk/Library/Caches/Homebrew/go--gobootstrap-10.8.tar.gz
==> ./make.bash --no-clean
Last 15 lines from /Users/kkashalk/Library/Logs/Homebrew/go/01.make.bash:
	/private/tmp/go-20170221-24186-1ablz6m/go/gobootstrap/src/cmd/go/pkg.go:899 +0x1fd fp=0xc2080add18 sp=0xc2080adc00
main.runClean(0x3f9ae0, 0xc20800a030, 0x1, 0x1)
	/private/tmp/go-20170221-24186-1ablz6m/go/gobootstrap/src/cmd/go/clean.go:78 +0x45 fp=0xc2080add98 sp=0xc2080add18
main.main()
	/private/tmp/go-20170221-24186-1ablz6m/go/gobootstrap/src/cmd/go/main.go:163 +0x608 fp=0xc2080adf98 sp=0xc2080add98
runtime.main()
	/usr/local/go/src/runtime/proc.go:63 +0xf3 fp=0xc2080adfe0 sp=0xc2080adf98
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc2080adfe8 sp=0xc2080adfe0

goroutine 5 [syscall]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/usr/local/go/src/os/signal/signal_unix.go:27 +0x35

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/brew):
  https://github.com/Homebrew/homebrew-core/issues

Warning: You are using OS X 10.12.
We do not provide support for this pre-release version.
You may encounter build failures or other breakages.
Please create pull-requests instead of filing issues.
```

**Comment by DomT4** [comment]
@kirankashalkar Your problem is that Homebrew is massively outdated on your machine. If `brew update` followed by `brew info go` doesn't show `go` at version `1.8` then you should:

```bash
cd "$(brew --repo)" && git fetch && git reset --hard origin/master && brew update
```
Then `brew install charm-tools` should work.

**Comment by kirankashalkar** [comment]
Thanks. That worked!

**Comment by kwmonroe** [comment]
Closing per previous comment.
