### ISSUE TITLE
metadata YAML error dumps stack trace

### ISSUE THREAD

**Issue by chuckbutler** [juju/charm-tools#31]
When opening the metadata.yaml of a charm layer, it dumps a long stack trace with an indicator of the error when using the currently available charm-tools from brew.  charm-tools-1.7.1-yosemite.bottle

```
 charm compose -o $JUJU_REPOSITORY
Traceback (most recent call last):
  File "/usr/local/Cellar/charm-tools/1.7.1/libexec/bin/charm-compose", line 9, in <module>
    load_entry_point('charm-tools==1.7.1', 'console_scripts', 'charm-compose')()
  File "/usr/local/Cellar/charm-tools/1.7.1/libexec/lib/python2.7/site-packages/charm_tools-1.7.1-py2.7.egg/charmtools/compose/__init__.py", line 468, in main
    composer()
  File "/usr/local/Cellar/charm-tools/1.7.1/libexec/lib/python2.7/site-packages/charm_tools-1.7.1-py2.7.egg/charmtools/compose/__init__.py", line 388, in __call__
    self.find_or_create_repo()
  File "/usr/local/Cellar/charm-tools/1.7.1/libexec/lib/python2.7/site-packages/charm_tools-1.7.1-py2.7.egg/charmtools/compose/__init__.py", line 180, in find_or_create_repo
    self.create_repo()
  File "/usr/local/Cellar/charm-tools/1.7.1/libexec/lib/python2.7/site-packages/charm_tools-1.7.1-py2.7.egg/charmtools/compose/__init__.py", line 166, in create_repo
    self.target_dir = (self.repo / self.name)
  File "/usr/local/Cellar/charm-tools/1.7.1/libexec/lib/python2.7/site-packages/charm_tools-1.7.1-py2.7.egg/charmtools/compose/__init__.py", line 138, in name
    data = yaml.load(md.open())
  File "/usr/local/Cellar/charm-tools/1.7.1/libexec/lib/python2.7/site-packages/PyYAML-3.11-py2.7-macosx-10.10-intel.egg/yaml/__init__.py", line 71, in load
  File "/usr/local/Cellar/charm-tools/1.7.1/libexec/lib/python2.7/site-packages/PyYAML-3.11-py2.7-macosx-10.10-intel.egg/yaml/constructor.py", line 37, in get_single_data
  File "/usr/local/Cellar/charm-tools/1.7.1/libexec/lib/python2.7/site-packages/PyYAML-3.11-py2.7-macosx-10.10-intel.egg/yaml/composer.py", line 36, in get_single_node
  File "/usr/local/Cellar/charm-tools/1.7.1/libexec/lib/python2.7/site-packages/PyYAML-3.11-py2.7-macosx-10.10-intel.egg/yaml/composer.py", line 55, in compose_document
  File "/usr/local/Cellar/charm-tools/1.7.1/libexec/lib/python2.7/site-packages/PyYAML-3.11-py2.7-macosx-10.10-intel.egg/yaml/composer.py", line 84, in compose_node
  File "/usr/local/Cellar/charm-tools/1.7.1/libexec/lib/python2.7/site-packages/PyYAML-3.11-py2.7-macosx-10.10-intel.egg/yaml/composer.py", line 127, in compose_mapping_node
  File "/usr/local/Cellar/charm-tools/1.7.1/libexec/lib/python2.7/site-packages/PyYAML-3.11-py2.7-macosx-10.10-intel.egg/yaml/parser.py", line 98, in check_event
  File "/usr/local/Cellar/charm-tools/1.7.1/libexec/lib/python2.7/site-packages/PyYAML-3.11-py2.7-macosx-10.10-intel.egg/yaml/parser.py", line 428, in parse_block_mapping_key
  File "/usr/local/Cellar/charm-tools/1.7.1/libexec/lib/python2.7/site-packages/PyYAML-3.11-py2.7-macosx-10.10-intel.egg/yaml/scanner.py", line 116, in check_token
  File "/usr/local/Cellar/charm-tools/1.7.1/libexec/lib/python2.7/site-packages/PyYAML-3.11-py2.7-macosx-10.10-intel.egg/yaml/scanner.py", line 220, in fetch_more_tokens
  File "/usr/local/Cellar/charm-tools/1.7.1/libexec/lib/python2.7/site-packages/PyYAML-3.11-py2.7-macosx-10.10-intel.egg/yaml/scanner.py", line 580, in fetch_value
yaml.scanner.ScannerError: mapping values are not allowed here
  in "./metadata.yaml", line 10, column 10
```

I think we have an opportunity to capture this and remove the stack, and instead error out stating the metadata.yaml has errors.

**Comment by marcoceppi** [comment]
Is this because of a malformed metadata.yaml? Could you post the
metadata.yaml file that created this?

**Comment by chuckbutler** [comment]
it was a malformed metadata.yaml, the yaml itself was invalid.

```
name: k8s
summary: The Kubernetes layer charm.
maintainers:
    - Matthew Bruzek <matthew.bruzek@ubuntu.com>
description: |
  Delivers the Kubernetes code as docker containers.
tags:
  - infrastructure
subordinate: false
 requires:
   etcd:
     interface: etcd
```

there's a space before 'requires' that will cause the parser to throw that stack trace, but it gives meaningful enough output as to what the issue is.
