### ISSUE TITLE
charm proof fails to find simplejson on macOS

### ISSUE THREAD

**Issue by kwmonroe** [juju/charm-tools#317]
## Checklist

 - [X] Confirmed this is an issue with charm-tools, not charmstore-client
 - [X] Provide versions of tools used
 - [X] Described the feature or ways to replicate the issue

## What version am I running?

I ran the following command: `charm version` and got the following ouput:

```
$ charm version
charm unavailable
charm-tools 2.2.0

$ brew info charm
charm: stable 2.2.2 (bottled)
Tool for managing Juju Charms
https://github.com/juju/charmstore-client
/usr/local/Cellar/charm/2.1.1 (2 files, 14.3MB)
  Poured from bottle on 2016-04-16 at 12:02:17
/usr/local/Cellar/charm/2.2.0 (4 files, 11.6MB)
  Poured from bottle on 2016-09-30 at 10:25:15
/usr/local/Cellar/charm/2.2.2 (5 files, 12.2MB) *
  Poured from bottle on 2017-04-03 at 11:04:04
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/charm.rb
==> Dependencies
Build: go ✔, bazaar ✔
==> Requirements
Build: git ✔

$ brew info charm-tools
charm-tools: stable 2.2.0 (bottled)
Tools for authoring and maintaining juju charms
https://github.com/juju/charm-tools
/usr/local/Cellar/charm-tools/2.1.2_1 (1,940 files, 19.9MB)
  Poured from bottle on 2017-02-20 at 11:08:57
/usr/local/Cellar/charm-tools/2.2.0 (2,067 files, 21MB) *
  Poured from bottle on 2017-04-03 at 11:04:09
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/charm-tools.rb
==> Dependencies
Required: libyaml ✔, charm ✔, openssl@1.1 ✔
==> Requirements
Required: mercurial ✔
```

I am using: ```macOS Sierra 10.12.4```

### I expect/expected the following

```
$ charm proof
Great job Kevin, this is the best charm ev4r.
```

### What I got

```
$ charm proof
Traceback (most recent call last):
  File "/usr/local/bin/charm-proof", line 11, in <module>
    load_entry_point('charm-tools==2.2.0', 'console_scripts', 'charm-proof')()
  File "/usr/local/Cellar/charm-tools/2.2.0/libexec/lib/python2.7/site-packages/pkg_resources/__init__.py", line 560, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/Cellar/charm-tools/2.2.0/libexec/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2648, in load_entry_point
    return ep.load()
  File "/usr/local/Cellar/charm-tools/2.2.0/libexec/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2302, in load
    return self.resolve()
  File "/usr/local/Cellar/charm-tools/2.2.0/libexec/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2308, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/Cellar/charm-tools/2.2.0/libexec/lib/python2.7/site-packages/charmtools/proof.py", line 23, in <module>
    from charms import Charm
  File "/usr/local/Cellar/charm-tools/2.2.0/libexec/lib/python2.7/site-packages/charmtools/charms.py", line 13, in <module>
    from launchpadlib.launchpad import Launchpad
  File "/usr/local/Cellar/charm-tools/2.2.0/libexec/lib/python2.7/site-packages/launchpadlib/launchpad.py", line 38, in <module>
    from lazr.restfulclient.resource import (
  File "/usr/local/Cellar/charm-tools/2.2.0/libexec/lib/python2.7/site-packages/lazr/restfulclient/resource.py", line 36, in <module>
    import simplejson
```

**Comment by chuckbutler** [comment]
I think this is a packaging issue, you get similar issue(s) from using the non-snap package of charm-tools on a fresh host install and it can be resolved by `pip install simplejson`.

just adding feedback here.
