### ISSUE TITLE
charm snap: pkg_resources.VersionConflict

### ISSUE THREAD

**Issue by nottrobin** [juju/charm-tools#319]
I installed the `charm` snap following [the documentation](https://jujucharms.com/docs/stable/tools-charm-tools), but when I try to run `charm create`, I get an error:

``` bash
$ which charm
/snap/bin/charm
$ charm create wsgi
INFO: Using default charm template (reactive-python). To select a different template, use the -t option.
Traceback (most recent call last):
  File "/snap/charm/15/bin/charm-create", line 11, in <module>
    sys.exit(main())
  File "/snap/charm/15/lib/python2.7/site-packages/charmtools/create.py", line 96, in main
    generator = CharmGenerator(args)
  File "/snap/charm/15/lib/python2.7/site-packages/charmtools/generators/generator.py", line 44, in __init__
    self.plugin = self._load_plugin()
  File "/snap/charm/15/lib/python2.7/site-packages/charmtools/generators/generator.py", line 53, in _load_plugin
    return ep.load()()
  File "/home/robin/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2301, in load
    self.require(*args, **kwargs)
  File "/home/robin/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2324, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/home/robin/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 859, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (requests 2.13.0 (/home/robin/.local/lib/python2.7/site-packages), Requirement.parse('requests<=2.9.1'))
```

**Comment by codersquid** [comment]
This is affecting me too.

**Comment by johnsca** [comment]
The confined snap was just released to stable, which should address this.  Please `snap refresh charm` and re-open if still an issue.
