### ISSUE TITLE
charm build fails w/ "AttributeError: 'module' object has no attribute 'HTTPSConnection'"

### ISSUE THREAD

**Issue by dannf** [juju/charm-tools#339]
# Checklist

 - [X] Confirmed this is an issue with charm-tools, not charmstore-client
 - [X] Provide versions of tools used
 - [ ] Described the feature or ways to replicate the issue

## What version am I running?

I ran the following command: `charm version` and got the following ouput:

```
charm 2.2.2
charm-tools 2.2.1
```
I ran the following command: `snap info charm` and got the following output:
```
name:      charm
summary:   "charm and charm-tools"
publisher: charms
description: |
  charmstore-client and charm-tools
snap-id: 2Rryoc2ylScfbFl4eQtpntHD9iuZuMvt
commands:
  - charm
tracking:    stable
installed:   2.2 (15) 48MB classic
refreshed:   2017-03-24 14:59:35 -0600 MDT
channels:             
  stable:    2.2 (15) 48MB  classic
  candidate: 2.2 (17) 102MB -
  beta:      ↑              
  edge:      2.2 (20) 102MB -
```
I am using: Debian unstable

### I expect/expected the following

Executing `charm build` would build my charm.

### What I got
```
dannf@xps13:~/git/java-browser-charm$ charm build
Traceback (most recent call last):
  File "/snap/charm/15/bin/charm-build", line 7, in <module>
    from charmtools.build.builder import main
  File "/snap/charm/15/lib/python2.7/site-packages/charmtools/build/__init__.py", line 6, in <module>
    from builder import (
  File "/snap/charm/15/lib/python2.7/site-packages/charmtools/build/builder.py", line 16, in <module>
    from charmtools import (utils, repofinder, proof)
  File "/snap/charm/15/lib/python2.7/site-packages/charmtools/proof.py", line 23, in <module>
    from charms import Charm
  File "/snap/charm/15/lib/python2.7/site-packages/charmtools/charms.py", line 13, in <module>
    from launchpadlib.launchpad import Launchpad
  File "/snap/charm/15/lib/python2.7/site-packages/launchpadlib/launchpad.py", line 33, in <module>
    from httplib2 import proxy_info_from_environment
  File "/snap/charm/15/lib/python2.7/site-packages/httplib2/__init__.py", line 960, in <module>
    class HTTPSConnectionWithTimeout(httplib.HTTPSConnection):
AttributeError: 'module' object has no attribute 'HTTPSConnection'
```

**Comment by johnsca** [comment]
This is actually an issue with the classic snap mixing with the environment and causing a Python lib version conflict.  The candidate channel snap is strictly confined, and we're working on getting that to stable shortly.

**Comment by johnsca** [comment]
The confined snap is now in the stable channel.  Please do a `snap refresh charm` and try again, and re-open if still an issue.
