### ISSUE TITLE
charm-build help errors

### ISSUE THREAD

**Issue by kat-co** [juju/charm-tools#35]
```shell
$ charm-build help                                                                      
build: Composing into help
Traceback (most recent call last):
  File "/usr/bin/charm-build", line 9, in <module>
    load_entry_point('charm-tools==1.8.0', 'console_scripts', 'charm-build')()
  File "/usr/lib/python2.7/dist-packages/charmtools/build/__init__.py", line 520, in main
    build()
  File "/usr/lib/python2.7/dist-packages/charmtools/build/__init__.py", line 422, in __call__
    self.generate()
  File "/usr/lib/python2.7/dist-packages/charmtools/build/__init__.py", line 385, in generate
    layers = self.fetch()
  File "/usr/lib/python2.7/dist-packages/charmtools/build/__init__.py", line 203, in fetch
    layer = Layer(self.charm, self.deps).fetch()
  File "/usr/lib/python2.7/dist-packages/charmtools/build/__init__.py", line 89, in fetch
    self.url, self.ENVIRON))
OSError: Unable to locate help. Do you need to set LAYER_PATH
```

I've tried setting LAYER_PATH to my charm's src directory where layers.yaml is located, but that doesn't seem to work either.

**Comment by mbruzek** [comment]
Hi @kat-co I am sorry for your bad experience with charm build.  I also get this same error message when issuing the same command.  The command you were looking for is: `charm build --help`

The reason you are seeing this error is because the command you issued is looking for a layer named "help".  The build command should not stack trace when the name is not found and should provide a proper error message with a usage.

How I found this out.  I ran the command with the -l DEBUG option and I could see better what was going on.
```sh
$ charm build help -l DEBUG
build: Composing into /home/mbruzek/workspace/charms
build: {
  "INTERFACE_PATH": null, 
  "JUJU_REPOSITORY": "/home/mbruzek/workspace/charms", 
  "LAYER_PATH": null, 
  "_charm": "help", 
  "_name": "help", 
  "config": "<charmtools.build.config.BuildConfig object at 0x7fa22646cd10>", 
  "deps": "/home/mbruzek/workspace/charms/deps", 
  "force": false, 
  "hide_metrics": true, 
  "interface_service": "http://interfaces.juju.solutions", 
  "log_level": "DEBUG", 
  "output_dir": "/home/mbruzek/workspace/charms", 
  "repo": "/home/mbruzek/workspace/charms/trusty", 
  "series": "trusty", 
  "target_dir": "/home/mbruzek/workspace/charms/trusty/help"
}
Traceback (most recent call last):
  File "/usr/local/bin/charm-build", line 9, in <module>
    load_entry_point('charm-tools==1.8.0', 'console_scripts', 'charm-build')()
  File "/usr/local/lib/python2.7/dist-packages/charmtools/build/__init__.py", line 520, in main
    build()
  File "/usr/local/lib/python2.7/dist-packages/charmtools/build/__init__.py", line 422, in __call__
    self.generate()
  File "/usr/local/lib/python2.7/dist-packages/charmtools/build/__init__.py", line 385, in generate
    layers = self.fetch()
  File "/usr/local/lib/python2.7/dist-packages/charmtools/build/__init__.py", line 203, in fetch
    layer = Layer(self.charm, self.deps).fetch()
  File "/usr/local/lib/python2.7/dist-packages/charmtools/build/__init__.py", line 89, in fetch
    self.url, self.ENVIRON))
OSError: Unable to locate help. Do you need to set LAYER_PATH?
```

You can see from the output above the _charm and _name values are "help" and they were looking for a directory named help.

Still a bug, we should never see a stack trace.  But I hope this workaround helps you while we fix it.

**Comment by johnsca** [comment]
I agree that a stack trace is not the most friendly way to report this error.  I also think it's worth special-casing the layer name `help` since the existence of `charm help` would lead me to expect `charm build help` to work, as well.

**Comment by bcsaller** [comment]
Fix committed
