### ISSUE TITLE
charm-tools 2.2.3 is not pip installable with py35

### ISSUE THREAD

**Issue by ryan-beisner** [juju/charm-tools#370]
```TypeError: the JSON object must be str, not 'bytes'```

```
ubuntu@beisner-bastion:~/temp⟫ virtualenv --python=python3.5 venv35
Running virtualenv with interpreter /usr/bin/python3.5
Using base prefix '/usr'
New python executable in /home/ubuntu/temp/venv35/bin/python3.5
Also creating executable in /home/ubuntu/temp/venv35/bin/python
Installing setuptools, pkg_resources, pip, wheel...done.
ubuntu@beisner-bastion:~/temp⟫ . venv35/bin/activate
(venv35) 130 ubuntu@beisner-bastion:~/temp⟫ pip install charm-tools
Collecting charm-tools
  Using cached charm-tools-2.2.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "/tmp/pip-build-ie1g5er5/charm-tools/charmtools/git_version.py", line 74, in <module>
        version_info = get_version_info()
      File "/tmp/pip-build-ie1g5er5/charm-tools/charmtools/git_version.py", line 18, in get_version_info
        version_info = json.loads(resource_string(__name__, 'VERSION'))
      File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
        s.__class__.__name__))
    TypeError: the JSON object must be str, not 'bytes'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-ie1g5er5/charm-tools/setup.py", line 13, in <module>
        version = subprocess.check_output([version_script, '--format=short']).strip()
      File "/usr/lib/python3.5/subprocess.py", line 626, in check_output
        **kwargs).stdout
      File "/usr/lib/python3.5/subprocess.py", line 708, in run
        output=stdout, stderr=stderr)
    subprocess.CalledProcessError: Command '['/tmp/pip-build-ie1g5er5/charm-tools/charmtools/git_version.py', '--format=short']' returned non-zero exit status 1
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-ie1g5er5/charm-tools/
(venv35) 1 ubuntu@beisner-bastion:~/temp⟫ 
```

**Comment by johnsca** [comment]
charm-tools is not currently compatible with Python 3.
