### ISSUE TITLE
charm version generator feature - builds fail if no vcs is present

### ISSUE THREAD

**Issue by ryan-beisner** [juju/charm-tools#468]
charm version generator feature - builds fail if no vcs is present
Feature implemented @ https://github.com/juju/charm-tools/pull/437

I think we should not require vcs in order to build.

Reproducer:

- Git clone a charm, cd to it.
- ```rm -rf .git```
- build the charm
- error:

```
utils: process: git describe --dirty --always (128)
utils: bzr: ERROR: Not a branch: "/home/ubuntu/git/charm-aodh/src/".

utils: process: bzr version-info (3)
Traceback (most recent call last):
  File "/home/ubuntu/git/charm-aodh/.tox/build/bin/charm-build", line 11, in <module>
    sys.exit(main())
  File "/home/ubuntu/git/charm-aodh/.tox/build/local/lib/python2.7/site-packages/charmtools/build/builder.py", line 834, in main
    build()
  File "/home/ubuntu/git/charm-aodh/.tox/build/local/lib/python2.7/site-packages/charmtools/build/builder.py", line 636, in __call__
    self.generate()
  File "/home/ubuntu/git/charm-aodh/.tox/build/local/lib/python2.7/site-packages/charmtools/build/builder.py", line 589, in generate
    self.exec_plan(self.plan, self.layers)
  File "/home/ubuntu/git/charm-aodh/.tox/build/local/lib/python2.7/site-packages/charmtools/build/builder.py", line 562, in exec_plan
    tactic()
  File "/home/ubuntu/git/charm-aodh/.tox/build/local/lib/python2.7/site-packages/charmtools/build/tactics.py", line 999, in __call__
    new_sha = self._try_to_get_current_sha()
  File "/home/ubuntu/git/charm-aodh/.tox/build/local/lib/python2.7/site-packages/charmtools/build/tactics.py", line 992, in _try_to_get_current_sha
    except FileNotFoundError as e:
NameError: global name 'FileNotFoundError' is not defined
ERROR: InvocationError: '/home/ubuntu/git/charm-aodh/.tox/build/bin/charm-build --log-level DEBUG -o /home/ubuntu/git/charm-aodh/build src'
___________________________________ summary ____________________________________
ERROR:   build: commands failed
```

**Comment by ryan-beisner** [comment]
```
(build) ubuntu@beisner-bastion:~/git/charm-aodh$ pip freeze | grep charm
snap charm-tools==2.4.5
libcharmstore==0.0.8
(build) ubuntu@beisner-bastion:~/git/charm-aodh$ snap info charm
name:      charm
summary:   charm and charm-tools
publisher: Cory Johns (johnsca)
contact:   juju@lists.ubuntu.com
license:   unset
description: |
  charmstore-client and charm-tools
commands:
  - charm
snap-id:      2Rryoc2ylScfbFl4eQtpntHD9iuZuMvt
tracking:     stable
refresh-date: 19 days ago, at 00:05 UTC
channels:                                    
  stable:    2.4.4                (254) 47MB classic
  candidate: 2.4.4                (254) 47MB classic
  beta:      2.4.4                (254) 47MB classic
  edge:      2.4.5+git-1-gd62c072 (277) 47MB classic
installed:   2.3.1                (212) 46MB -
```

**Comment by ryan-beisner** [comment]
Attaching a full build output:

[build-result.txt](https://github.com/juju/charm-tools/files/2516081/build-result.txt)

**Comment by ryan-beisner** [comment]
The impact of this, is that after our charm have gone through gerrit, there is a blob artifact that can be downloaded and built for further verification by devs/reviewers.  However, it no longer builds due to the above.

**Comment by ryan-beisner** [comment]
Use of ```FileNotFoundError``` assumes Python >= 3.5, however the library unit tests and distribution supports Py27.

**Comment by stub42** [comment]
Per traceback, charm-build is not running from the snap, but instead a copy of charm-tools installed in the Python2 tox venv. I think either something other than '/snap/bin/charm build' is being invoked, or the snap needs to ensure that the PATH is correctly setup so that /snap/bin/charm will invoke /snap/charm/current/bin/charm-build.

**Comment by ryan-beisner** [comment]
@stub42 Indeed.  We still consume charm-build in a pure python virtualenv upstream @ OpenStack.
