### ISSUE TITLE
charm build in an empty directory yeilds a python traceback

### ISSUE THREAD

**Issue by mbruzek** [juju/charm-tools#49]
The charm build command in an empty directory fails with a python traceback.  I do expect the command to fail, but it should provide a better error message.

```
mbruzek@warhorse:/tmp/foo$ charm build
build: Composing into .
build: The top level layer expects a valid layer.yaml file, using defaults.
build: Processing layer: foo
Traceback (most recent call last):
  File "/usr/local/bin/charm-build", line 9, in <module>
    load_entry_point('charm-tools==1.8.0', 'console_scripts', 'charm-build')()
  File "/usr/local/lib/python2.7/dist-packages/charmtools/build/__init__.py", line 520, in main
    build()
  File "/usr/local/lib/python2.7/dist-packages/charmtools/build/__init__.py", line 422, in __call__
    self.generate()
  File "/usr/local/lib/python2.7/dist-packages/charmtools/build/__init__.py", line 387, in generate
    self.exec_plan(self.plan, self.layers)
  File "/usr/local/lib/python2.7/dist-packages/charmtools/build/__init__.py", line 374, in exec_plan
    self.write_signatures(signatures, layers)
  File "/usr/local/lib/python2.7/dist-packages/charmtools/build/__init__.py", line 382, in write_signatures
    ), indent=2))
  File "/usr/local/lib/python2.7/dist-packages/path.py", line 870, in write_text
    self.write_bytes(text, append=append)
  File "/usr/local/lib/python2.7/dist-packages/path.py", line 784, in write_bytes
    with self.open(mode) as f:
  File "/usr/local/lib/python2.7/dist-packages/path.py", line 749, in open
    return io.open(self, *args, **kwargs)
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/path.py", line 106, in io_error_compat
    raise os_err
OSError: [Errno 2] No such file or directory: './trusty/foo/.build.manifest'
```

**Comment by mbruzek** [comment]
Adding the DEBUG log 

```
build: {
  "INTERFACE_PATH": null, 
  "JUJU_REPOSITORY": null, 
  "LAYER_PATH": null, 
  "_charm": ".", 
  "_name": "mbruzek", 
  "config": "<charmtools.build.config.BuildConfig object at 0x7fea88947250>", 
  "deps": "./deps", 
  "force": false, 
  "hide_metrics": true, 
  "interface_service": "http://interfaces.juju.solutions", 
  "log_level": "DEBUG", 
  "output_dir": ".", 
  "repo": "./trusty", 
  "series": "trusty", 
  "target_dir": "./trusty/mbruzek"
}
```

**Comment by marcoceppi** [comment]
This just needs some more clever error handling
