### ISSUE TITLE
Default cache dir value prevents building multiple charms simultaneously

### ISSUE THREAD

**Issue by knkski** [juju/charm-tools#517]
## Checklist

 - [X] Confirmed this is an issue with charm-tools, not charmstore-client
 - [X] Provide versions of tools used
 - [X] Described the feature or ways to replicate the issue

## What version am I running?

```
name:      charm
summary:   charm and charm-tools
publisher: Cory Johns (johnsca)
contact:   juju@lists.ubuntu.com
license:   unset
description: |
  charmstore-client and charm-tools
commands:
  - charm
snap-id:      2Rryoc2ylScfbFl4eQtpntHD9iuZuMvt
tracking:     edge
refresh-date: today at 17:02 CDT
channels:
  stable:    2.5.2                2019-02-07 (320) 47MB classic
  candidate: 2.5.2                2019-02-07 (320) 47MB classic
  beta:      2.5.2                2019-02-07 (320) 47MB classic
  edge:      2.5.2+git-17-099a2c7 2019-04-05 (331) 57MB classic
installed:   2.5.2+git-17-099a2c7            (331) 57MB classic
```

I am using: (Your operating system)

Ubuntu 18.04

### I expect/expected the following

I am attempting to build several different charms as part of a bundle, and I expected to be able to simultaneously.

### What I got

Building serially worked great, but building concurrently produced a few copies of this error:

```python
Traceback (most recent call last):
  File "/snap/charm/331/bin/charm-build", line 11, in <module>
    load_entry_point('charm-tools==2.5.2', 'console_scripts', 'charm-build')()
  File "/snap/charm/331/lib/python3.6/site-packages/charmtools/build/builder.py", line 936, in main
    build()
  File "/snap/charm/331/lib/python3.6/site-packages/charmtools/build/builder.py", line 649, in __call__
    self.generate()
  File "/snap/charm/331/lib/python3.6/site-packages/charmtools/build/builder.py", line 592, in generate
    layers = self.fetch()
  File "/snap/charm/331/lib/python3.6/site-packages/charmtools/build/builder.py", line 273, in fetch
    return self.fetch_deps(self.top_layer)
  File "/snap/charm/331/lib/python3.6/site-packages/charmtools/build/builder.py", line 278, in fetch_deps
    self.fetch_dep(layer, results)
  File "/snap/charm/331/lib/python3.6/site-packages/charmtools/build/builder.py", line 313, in fetch_dep
    base_layer.fetch()
  File "/snap/charm/331/lib/python3.6/site-packages/charmtools/build/builder.py", line 100, in fetch
    self.directory = path(fetcher.fetch(self.target_repo))
  File "/snap/charm/331/lib/python3.6/site-packages/charmtools/build/fetchers.py", line 160, in fetch
    shutil.copytree(res, target)
  File "/snap/charm/331/usr/lib/python3.6/shutil.py", line 359, in copytree
    raise Error(errors)
shutil.Error: [(Path('~/.cache/charm/layer/tmpb_62anm2/.git'), Path('~/.cache/charm/layer/caas-base/.git'), "[Errno 17] File exists: Path('~/.cache/charm/layer/caas-base/.git')")]
```

### Resoluion

I solved the immediate issue by passing in the `--cache-dir` option and pointing at `~/.cache/charm/$CHARM_NAME` instead of just `~/.cache/charm/`. However, it seems like we may want to switch the default to be namespaced to the charm name. We don't currently have this issue now to my knowledge since the latest version of each layer is always used, but we may potentially have conflicting layer versions in the future in different charms that we wouldn't want to cross-cache.

**Comment by johnsca** [comment]
Possibly related to #487
