### ISSUE TITLE
vergit is an undocumented dependency

### ISSUE THREAD

**Issue by ChrisMacNaughton** [juju/charm-tools#518]
Installing the charm-tools package into a virtualenv now requires the `vergit` python package to be available

## Checklist

 - [X] Confirmed this is an issue with charm-tools, not charmstore-client
 - [X] Provide versions of tools used
 - [X] Described the feature or ways to replicate the issue

## What version am I running?

Master

```
pip install -e git+https://github.com/juju/charm-tools.git
```

I am using: Ubuntu Disco

### I expect/expected the following

charm-tools to be installed in my virtualenv

### What I got

```
Obtaining charm-tools from git+https://github.com/juju/charm-tools.git#egg=charm-tools (from -r /home/chris/code/centauri/charms/snmpd/requirements.txt (line 2))
  Cloning https://github.com/juju/charm-tools.git to ./.tox/build/src/charm-tools
  Running command git clone -q https://github.com/juju/charm-tools.git /home/chris/code/centauri/charms/snmpd/.tox/build/src/charm-tools
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/chris/code/centauri/charms/snmpd/.tox/build/src/charm-tools/setup.py", line 15, in <module>
        version_raw = subprocess.check_output(['vergit', '--format=json']).strip()
      File "/usr/lib/python3.7/subprocess.py", line 395, in check_output
        **kwargs).stdout
      File "/usr/lib/python3.7/subprocess.py", line 472, in run
        with Popen(*popenargs, **kwargs) as process:
      File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
        restore_signals, start_new_session)
      File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: 'vergit': 'vergit'
```

**Comment by johnsca** [comment]
@ChrisMacNaughton Can you confirm that the latest master works for the OpenStack builds?  I'd like to do a release to stable & pypi.

**Comment by ChrisMacNaughton** [comment]
using this super basic virtualenv config: https://gist.github.com/ChrisMacNaughton/3043f13d06427383d103bf518d193c71

I end up getting:

```
# tox -e venv                                                                                                                                                                                     
venv create: /root/test/.tox/venv                                
venv installdeps: -r/root/test/requirements.txt
ERROR: invocation failed (exit code 1), logfile: /root/test/.tox/venv/log/venv-1.log
ERROR: actionid: venv                                                           
msg: getenv                                 
cmdargs: ['/root/test/.tox/venv/bin/pip', 'install', '-r/root/test/requirements.txt']                                                                                                                             
env: {'LS_COLORS': 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=
01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=0
1;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.z
oo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=0
1;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;3
5:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=0
1;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.
oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:', 'LESSCLOSE': '/usr/bin/lesspipe %s %s', 'LANG': 'C.UTF-8', 'container': 'lxc', 'USER': 'root', 'PWD': '/root/test', 'HOME': '/root', 'TERM': 'linux', 'SHLVL': '
1', 'PATH': '/root/test/.tox/venv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin', 'LESSOPEN': '| /usr/bin/lesspipe %s', '_': '/usr/bin/tox', 'OLDPWD': '/root', 'VIRTUAL_ENV': '/root/
test/.tox/venv', 'PYTHONHASHSEED': '0'}

Obtaining charm-tools from git+https://github.com/juju/charm-tools.git#egg=charm-tools (from -r /root/test/requirements.txt (line 2))
  Cloning https://github.com/juju/charm-tools.git to ./.tox/venv/src/charm-tools
  Running command git clone -q https://github.com/juju/charm-tools.git /root/test/.tox/venv/src/charm-tools
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/root/test/.tox/venv/src/charm-tools/setup.py", line 24, in <module>
        with open(version_cache, 'r') as fh:
    FileNotFoundError: [Errno 2] No such file or directory: '/root/test/.tox/venv/src/charm-tools/charmtools/VERSION'
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /root/test/.tox/venv/src/charm-tools/
                   
ERROR: could not install deps [-r/root/test/requirements.txt]; v = InvocationError('/root/test/.tox/venv/bin/pip install -r/root/test/requirements.txt (see /root/test/.tox/venv/log/venv-1.log)', 1)
_____________________________________________________________________________________________________ summary _____________________________________________________________________________________________________
ERROR:   venv: could not install deps [-r/root/test/requirements.txt]; v = InvocationError('/root/test/.tox/venv/bin/pip install -r/root/test/requirements.txt (see /root/test/.tox/venv/log/venv-1.log)', 1)

```
