### ISSUE TITLE
charm-tools python pkg fails to install under Python 3.7

### ISSUE THREAD

**Issue by ryan-beisner** [juju/charm-tools#524]
charm-tools (dependencies) fail to install under Python 3.7.  This means that the next LTS (20.04) is problematic for charm-tools.

OpenStack Charms (and upstream OpenStack) are enabling Py37 now, and this issue blocks charm testing past Py36.

```
beisner@rby:~/temp$ virtualenv -p /usr/bin/python3.7 venv
Running virtualenv with interpreter /usr/bin/python3.7
Using base prefix '/usr'
/usr/lib/python3/dist-packages/virtualenv.py:1090: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses                               
  import imp
New python executable in /home/beisner/temp/venv/bin/python3.7
Also creating executable in /home/beisner/temp/venv/bin/python
Installing setuptools, pkg_resources, pip, wheel...done.
beisner@rby:~/temp$ . venv/bin/activate
(venv) beisner@rby:~/temp$ pip install charm-tools
Collecting charm-tools
  Using cached https://files.pythonhosted.org/packages/14/c6/82503c2835948e887f4789332cfcc4828509c1f389eb0ebecdc850c82522/charm-tools-2.5.1.tar.gz                                                            
Collecting launchpadlib<1.11 (from charm-tools)
  Using cached https://files.pythonhosted.org/packages/a3/14/74ab750a0e0c4b31c554614f93d3240db45a096bd29a8eed420960c7b597/launchpadlib-1.10.7.tar.gz                                                          
Collecting cheetah3>=3.0.0 (from charm-tools)
  Using cached https://files.pythonhosted.org/packages/8c/39/13d33f2bb40a132c069696c16324e3c7eed2f301a23f026ad519f0289c22/Cheetah3-3.2.3-cp37-cp37m-manylinux1_x86_64.whl                                     
Collecting pyyaml==3.11 (from charm-tools)
  Using cached https://files.pythonhosted.org/packages/75/5e/b84feba55e20f8da46ead76f14a3943c8cb722d40360702b2365b91dec00/PyYAML-3.11.tar.gz                                                                  
Collecting requests<=2.19.1 (from charm-tools)
  Using cached https://files.pythonhosted.org/packages/65/47/7e02164a2a3db50ed6d8a6ab1d6d60b69c4c3fdf57a284257925dfc12bda/requests-2.19.1-py2.py3-none-any.whl                                                
Collecting libcharmstore (from charm-tools)
  Using cached https://files.pythonhosted.org/packages/bc/83/c97392aa3ab2c2fd81a4e8896d986d59f7087342b71fed9d2168ada7589d/libcharmstore-0.0.9.tar.gz                                                          
Collecting blessings<=1.6 (from charm-tools)
  Using cached https://files.pythonhosted.org/packages/af/4a/61acd1c6c29662d3fcbcaee5ba95c20b1d315c5a33534732b6d81e0dc8e8/blessings-1.6.tar.gz                                                                
Collecting ruamel.yaml<=0.10.23 (from charm-tools)
  Using cached https://files.pythonhosted.org/packages/e1/fe/0021f94b54f7aa5a730b765f5a4eead9675be98c7f46c206c240fb9ef819/ruamel.yaml-0.10.23.tar.gz                                                          
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Warning: 'keywords' should be a list, got type 'NoneType'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-azbm5v7n/ruamel.yaml/setup.py", line 705, in <module>
        main()
      File "/tmp/pip-install-azbm5v7n/ruamel.yaml/setup.py", line 702, in main
        setup(**kw)
      File "/home/beisner/temp/venv/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup                                                                                                   
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.7/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/home/beisner/temp/venv/lib/python3.7/site-packages/setuptools/dist.py", line 444, in __init__                                                                                                    
        k: v for k, v in attrs.items()
      File "/usr/lib/python3.7/distutils/dist.py", line 267, in __init__
        getattr(self.metadata, "set_" + key)(val)
      File "/usr/lib/python3.7/distutils/dist.py", line 1203, in set_keywords
        self.keywords = _ensure_list(value, 'keywords')
      File "/usr/lib/python3.7/distutils/dist.py", line 40, in _ensure_list
        value = list(value)
    TypeError: 'NoneType' object is not iterable
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-azbm5v7n/ruamel.yaml/                                                                                                  
(venv) 1 beisner@rby:~/temp$ 
```

**Comment by ryan-beisner** [comment]
FYI, current version of ruamel.yaml installs ok:
```
(venv) beisner@rby:~/temp$ pip install ruamel.yaml
Collecting ruamel.yaml
  Downloading https://files.pythonhosted.org/packages/ae/77/1bb630e3873e9ffa617ba1a659e52f0030fc9c024847ef357c781b69a33a/ruamel.yaml-0.15.96-cp37-cp37m-manylinux1_x86_64.whl (648kB)
     |████████████████████████████████| 655kB 1.6MB/s 
Installing collected packages: ruamel.yaml
Successfully installed ruamel.yaml-0.15.96
```

I will look into revving up that dependency in a PR...

**Comment by ryan-beisner** [comment]
It turns out, this was already solved in @master by https://github.com/juju/charm-tools/pull/489, but it is not released to pypi.

I think all that we need is a pypi release to address this issue.

**Comment by ryan-beisner** [comment]
It looks like 2.6.0 is released on pypi https://pypi.org/project/charm-tools/#history and a couple of spot-checks in previously-failing scenarios are now resolved for me.
