### ISSUE TITLE
charm-tools python package doesn't declare vergit dependency

### ISSUE THREAD

**Issue by ryan-beisner** [juju/charm-tools#526]
The charm-tools python package doesn't declare vergit dependency, resuilting in charm build failures when used in a clean virtualenv.

```
beisner@rby:~/git/charm-octavia$ tox -e build
build create: /home/beisner/git/charm-octavia/.tox/build
build installdeps: -r/home/beisner/git/charm-octavia/requirements.txt
build installed: asn1crypto==0.24.0,blessings==1.6,certifi==2019.3.9,cffi==1.12.3,chardet==3.0.4,charm-tools==0.0.0,Cheetah3==3.2.3,colander==1.7.0,cryptography==2.7,dict2colander==0.2,distro==1.4.0,entrypoints==0.3,httplib2==0.12.3,idna==2.7,importlib-metadata==0.17,ipaddress==1.0.22,iso8601==0.1.12,jsonschema==2.5.1,jujubundlelib==0.5.6,keyring==19.0.2,launchpadlib==1.10.7,lazr.restfulclient==0.14.2,lazr.uri==1.0.3,libcharmstore==0.0.9,macaroonbakery==1.2.3,oauthlib==3.0.1,otherstuf==1.1.0,parse==1.12.0,path.py==12.0.1,pathspec==0.3.4,pbr==5.2.1,pkg-resources==0.0.0,protobuf==3.8.0,pycparser==2.19,pymacaroons==0.13.0,PyNaCl==1.3.0,pyRFC3339==1.1,pytz==2019.1,PyYAML==3.13,requests==2.20.1,ruamel.yaml==0.15.96,SecretStorage==2.3.1,simplejson==3.16.0,six==1.12.0,stuf==0.9.16,testresources==2.0.1,theblues==0.5.1,translationstring==1.3,urllib3==1.24.3,virtualenv==16.6.0,wadllib==1.3.3,zipp==0.5.1
build run-test-pre: PYTHONHASHSEED='0'
build runtests: commands[0] | charm-build --log-level DEBUG -o /home/beisner/git/charm-octavia/build src
Traceback (most recent call last):
  File "/home/beisner/git/charm-octavia/.tox/build/bin/charm-build", line 6, in <module>
    from charmtools.build.builder import main
  File "/home/beisner/git/charm-octavia/.tox/build/lib/python3.7/site-packages/charmtools/__init__.py", line 25, in <module>
    from . import version
  File "/home/beisner/git/charm-octavia/.tox/build/lib/python3.7/site-packages/charmtools/version.py", line 12, in <module>
    from vergit import format_version
ModuleNotFoundError: No module named 'vergit'
ERROR: InvocationError for command '/home/beisner/git/charm-octavia/.tox/build/bin/charm-build --log-level DEBUG -o /home/beisner/git/charm-octavia/build src' (exited with code 1)
___________________________________________________________________________________________________ summary ___________________________________________________________________________________________________
ERROR:   build: commands failed
```

**Comment by ryan-beisner** [comment]
I've raised https://github.com/juju/charm-tools/pull/527 to address this.

**Comment by johnsca** [comment]
vergit is not intended to be an installation-time dependency. This should have been addressed by #519 and #520 so it seems like there's another corner case that needs to be addressed.

**Comment by ryan-beisner** [comment]
Reproducer is to build a new virtualenv, pip install charm-tools from master, then simply call charm-build:

```
beisner@rby:~/temp$ virtualenv -p /usr/bin/python3.7 venv
Running virtualenv with interpreter /usr/bin/python3.7
Using base prefix '/usr'
/usr/lib/python3/dist-packages/virtualenv.py:1090: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
New python executable in /home/beisner/temp/venv/bin/python3.7
Also creating executable in /home/beisner/temp/venv/bin/python
Installing setuptools, pkg_resources, pip, wheel...done.

beisner@rby:~/temp$


beisner@rby:~/temp$ . venv/bin/activate                                        
(venv) beisner@rby:~/temp$ pip install git+https://github.com/juju/charm-tools@master                                                                                                                         
Collecting git+https://github.com/juju/charm-tools@master                   
  Cloning https://github.com/juju/charm-tools (to revision master) to /tmp/pip-req-build-b3s6tcwn                                                                                                             
  Running command git clone -q https://github.com/juju/charm-tools /tmp/pip-req-build-b3s6tcwn 
Collecting launchpadlib<1.11 (from charm-tools==0.0.0)                                        
Collecting cheetah3>=3.0.0 (from charm-tools==0.0.0)                             
  Using cached https://files.pythonhosted.org/packages/8c/39/13d33f2bb40a132c069696c16324e3c7eed2f301a23f026ad519f0289c22/Cheetah3-3.2.3-cp37-cp37m-manylinux1_x86_64.whl
Collecting pyyaml<4.3,>=3.11 (from charm-tools==0.0.0)                                    
...snip...
Successfully built charm-tools
Installing collected packages: oauthlib, distro, lazr.uri, wadllib, six, httplib2, lazr.restfulclient, pbr, testresources, entrypoints, pycparser, cffi, asn1crypto, cryptography, secretstorage, keyring, launchpadlib, cheetah3, pyyaml, certifi, urllib3, chardet, idna, requests, PyNaCl, pymacaroons, protobuf, pytz, pyRFC3339, ipaddress, macaroonbakery, jujubundlelib, theblues, libcharmstore, blessings, ruamel.yaml, pathspec, parse, stuf, otherstuf, zipp, importlib-metadata, path.py, virtualenv, iso8601, translationstring, colander, jsonschema, dict2colander, charm-tools
Successfully installed PyNaCl-1.3.0 asn1crypto-0.24.0 blessings-1.6 certifi-2019.3.9 cffi-1.12.3 chardet-3.0.4 charm-tools-0.0.0 cheetah3-3.2.3 colander-1.7.0 cryptography-2.7 dict2colander-0.2 distro-1.4.0 entrypoints-0.3 httplib2-0.12.3 idna-2.7 importlib-metadata-0.17 ipaddress-1.0.22 iso8601-0.1.12 jsonschema-2.5.1 jujubundlelib-0.5.6 keyring-19.0.2 launchpadlib-1.10.7 lazr.restfulclient-0.14.2 lazr.uri-1.0.3 libcharmstore-0.0.9 macaroonbakery-1.2.3 oauthlib-3.0.1 otherstuf-1.1.0 parse-1.12.0 path.py-12.0.1 pathspec-0.3.4 pbr-5.2.1 protobuf-3.8.0 pyRFC3339-1.1 pycparser-2.19 pymacaroons-0.13.0 pytz-2019.1 pyyaml-3.13 requests-2.20.1 ruamel.yaml-0.15.96 secretstorage-2.3.1 six-1.12.0 stuf-0.9.16 testresources-2.0.1 theblues-0.5.1 translationstring-1.3 urllib3-1.24.3 virtualenv-16.6.0 wadllib-1.3.3 zipp-0.5.1
(venv) beisner@rby:~/temp$ 
(venv) beisner@rby:~/temp$ charm-build
Traceback (most recent call last):
  File "/home/beisner/temp/venv/bin/charm-build", line 6, in <module>
    from charmtools.build.builder import main
  File "/home/beisner/temp/venv/lib/python3.7/site-packages/charmtools/__init__.py", line 25, in <module>
    from . import version
  File "/home/beisner/temp/venv/lib/python3.7/site-packages/charmtools/version.py", line 12, in <module>
    from vergit import format_version
ModuleNotFoundError: No module named 'vergit'
```

**Comment by ryan-beisner** [comment]
This is merged: https://github.com/juju/charm-tools/pull/527.  However, I failed in my git-fu closes-bug magic, so I'm closing my issue manually.  Thanks for the review and merge.
