### ISSUE TITLE
requirements.txt limits requests<=2.20.1 which will conflict with other packages like charm-keystone

### ISSUE THREAD

**Issue by guoqiao** [juju/charm-tools#535]
## Checklist

 - [X] Confirmed this is an issue with charm-tools, not charmstore-client
 - [X] Provide versions of tools used
 - [X] Described the feature or ways to replicate the issue

## What version am I running?

I ran the following command: `pip freeze | grep charm-tools` and got the following ouput:                                                                            
```
charm-tools==2.6.0
```

I am using: Ubuntu 18.04 LTS

## Issue/Feature
In `requirements.txt`:

    requests<=2.20.1

This stops latest `requests` versions to be installed, and may conflict with other packages' requirements.

For example, in [charm-keystone/test-requirements.txt#L2](https://github.com/openstack/charm-keystone/blob/15250435f69b6ca4ed024bb68d941243fa57bcde/test-requirements.txt#L2)  :

    charm-tools>=2.4.4
    requests>=2.18.4

According to [pip document](https://pip.pypa.io/en/stable/user_guide/#id12), 

> As it is now, pip doesn’t have true dependency resolution, but instead simply uses the first specification it finds for a project.

This implies, pip will find the top level explicit requirement `requests>=2.18.4` and end up installing the latest version (2.2.0), which conflicts with `charm-tools`.

### I expect/expected the following

In `charm-keystone`, run `tox -e pep8` should succeed.

### What I got
```
Traceback (most recent call last):
  File "/home/guoqiao/git/charm-keystone/.tox/pep8/bin/charm-proof", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/home/guoqiao/git/charm-keystone/.tox/pep8/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3241, in <module>
    @_call_aside
  File "/home/guoqiao/git/charm-keystone/.tox/pep8/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3225, in _call_aside
    f(*args, **kwargs)
  File "/home/guoqiao/git/charm-keystone/.tox/pep8/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3254, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/guoqiao/git/charm-keystone/.tox/pep8/lib/python3.6/site-packages/pkg_resources/__init__.py", line 585, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/home/guoqiao/git/charm-keystone/.tox/pep8/lib/python3.6/site-packages/pkg_resources/__init__.py", line 598, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/home/guoqiao/git/charm-keystone/.tox/pep8/lib/python3.6/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'requests<=2.20.1' distribution was not found and is required by charm-tools
```

**Comment by guoqiao** [comment]
Instead of limit maximum version, normally we should limit minimal version, except there is special reason.
According to [requests doc](https://2.python-requests.org/en/master/):
> Requests 2.x is officially in maintenance-mode only.
So the right version limit could be 2.0.0 <= version < 3.0.0, a PR #536 already created.
