### ISSUE TITLE
charm build broken on 2.7.3; working on 2.7.2

### ISSUE THREAD

**Issue by joedborg** [juju/charm-tools#559]
```
containerd on  master 
➜ charm build .
build: Destination charm directory: /tmp/builds/containerd
build: Processing layer: layer:options
build: Processing layer: layer:basic
build: Processing layer: layer:debug
build: Processing layer: layer:container-runtime-common (from ../container-runtime-common)
build: Processing layer: containerd (from .)
build: Processing interface: container-runtime (from ../container-runtime)
build: Processing interface: untrusted-container-runtime (from ../untrusted-container-runtime)
build: Processing interface: docker-registry
Traceback (most recent call last):
  File "/snap/charm/440/bin/virtualenv", line 5, in <module>
    from virtualenv.__main__ import run_with_catch
ModuleNotFoundError: No module named 'virtualenv.__main__'; 'virtualenv' is not a package

Command failed: virtualenv --python python3 /tmp/tmpgjnfmot4

containerd on  master took 7s 
➜ snap revert charm 
charm reverted to 2.7.2

containerd on  master 
➜ charm build .     
build: Destination charm directory: /tmp/builds/containerd
build: Processing layer: layer:options
build: Processing layer: layer:basic
build: Processing layer: layer:debug
build: Processing layer: layer:container-runtime-common (from ../container-runtime-common)
build: Processing layer: containerd (from .)
build: Processing interface: container-runtime (from ../container-runtime)
build: Processing interface: untrusted-container-runtime (from ../untrusted-container-runtime)
build: Processing interface: docker-registry
proof: I: `display-name` not provided, add for custom naming in the UI
```
I'm on 18.04 and have checked that no PYTHONPATH etc is set.

**Comment by johnsca** [comment]
@knkski got a very similar error:

```
$  charm build --debug charms/prometheus/ --cache-dir ~/.cache/charm/prometheus/
build: {
  "CHARM_BUILD_DIR": null,
  "CHARM_INTERFACES_DIR": "/home/knkski/charms/interfaces",
  "CHARM_LAYERS_DIR": "/home/knkski/charms/layers",
  "INTERFACE_PATH": null,
  "JUJU_REPOSITORY": "/home/knkski/charms",
  "LAYER_PATH": null,
  "_charm": "charms/prometheus/",
  "_charm_metadata": {
    "description": "Prometheus",
    "display-name": "Prometheus",
    "maintainers": [
      "Juju Developers <juju@lists.ubuntu.com>"
    ],
    "name": "prometheus",
    "provides": {
      "prometheus": {
        "interface": "http"
      }
    },
    "resources": {
      "oci-image": {
        "auto-fetch": true,
        "description": "Backing OCI image",
        "type": "oci-image",
        "upstream-source": "docker.io/prom/prometheus:v2.8.0"
      }
    },
    "series": [
      "kubernetes"
    ],
    "summary": "Prometheus",
    "tags": [
      "kubeflow",
      "reverse-proxy",
      "service-mesh"
    ]
  },
  "_name": null,
  "_top_layer": null,
  "_warned_home": false,
  "build_dir": "/home/knkski/charms/builds",
  "cache_dir": "/home/knkski/.cache/charm/prometheus/2820601",
  "config": "BuildConfig({'_tactics': [], 'configured': False})",
  "debug": true,
  "description": false,
  "force": false,
  "force_color": false,
  "hide_metrics": false,
  "interface_service": null,
  "layer_index": null,
  "log_level": 10,
  "no_local_layers": false,
  "output_dir": null,
  "report": false,
  "series": null,
  "verbose": false,
  "wheelhouse_overrides": null
}
charmtools.fetchers: git rev-parse HEAD: b'7a6b1548c732705e92c3aab65b524b29f3bbd998\n'
build: Destination charm directory: /home/knkski/charms/builds/prometheus
charmtools.build.fetchers: Checking layer index: https://juju.github.io/layer-index/layers/caas-base.json
charmtools.build.fetchers: Found repo: https://github.com/juju-solutions/layer-caas-base.git
charmtools.fetchers: git clone https://github.com/juju-solutions/layer-caas-base.git /home/knkski/.cache/charm/prometheus/2820601/layer/tmpopi7dece: b"Cloning into '/home/knkski/.cache/charm/prometheus/2820601/layer/tmpopi7dece'...\nwarning: templates not found /snap/charm/440/share/git-core/templates\n"
charmtools.fetchers: git rev-parse HEAD: b'fac96d3e2cc3b67fd450985800377643e8e13c73\n'
charmtools.build.fetchers: Copying /home/knkski/.cache/charm/prometheus/2820601/layer/tmpopi7dece to /home/knkski/.cache/charm/prometheus/2820601/layer/caas-base
charmtools.build.fetchers: Cleaning up /home/knkski/.cache/charm/prometheus/2820601/layer/tmpopi7dece
charmtools.build.fetchers: Checking layer index: https://juju.github.io/layer-index/layers/options.json
charmtools.build.fetchers: Found repo: https://github.com/juju-solutions/layer-options.git
charmtools.fetchers: git clone https://github.com/juju-solutions/layer-options.git /home/knkski/.cache/charm/prometheus/2820601/layer/tmpi8_5auwa: b"Cloning into '/home/knkski/.cache/charm/prometheus/2820601/layer/tmpi8_5auwa'...\nwarning: templates not found /snap/charm/440/share/git-core/templates\n"
charmtools.fetchers: git rev-parse HEAD: b'fcdcea4e5de3e1556c24e6704607862d0ba00a56\n'
charmtools.build.fetchers: Copying /home/knkski/.cache/charm/prometheus/2820601/layer/tmpi8_5auwa to /home/knkski/.cache/charm/prometheus/2820601/layer/options
charmtools.build.fetchers: Cleaning up /home/knkski/.cache/charm/prometheus/2820601/layer/tmpi8_5auwa
charmtools.build.fetchers: Checking layer index: https://juju.github.io/layer-index/layers/docker-resource.json
charmtools.build.fetchers: Found repo: https://github.com/juju-solutions/layer-docker-resource.git
charmtools.fetchers: git clone https://github.com/juju-solutions/layer-docker-resource.git /home/knkski/.cache/charm/prometheus/2820601/layer/tmpj0xjo1px: b"Cloning into '/home/knkski/.cache/charm/prometheus/2820601/layer/tmpj0xjo1px'...\nwarning: templates not found /snap/charm/440/share/git-core/templates\n"
charmtools.fetchers: git rev-parse HEAD: b'faea7f1e47c78932534d57037e283a265536bda9\n'
charmtools.build.fetchers: Copying /home/knkski/.cache/charm/prometheus/2820601/layer/tmpj0xjo1px to /home/knkski/.cache/charm/prometheus/2820601/layer/docker-resource
charmtools.build.fetchers: Cleaning up /home/knkski/.cache/charm/prometheus/2820601/layer/tmpj0xjo1px
charmtools.build.fetchers: Checking layer index: https://juju.github.io/layer-index/layers/status.json
charmtools.build.fetchers: Found repo: https://github.com/juju-solutions/layer-status
charmtools.fetchers: git clone https://github.com/juju-solutions/layer-status /home/knkski/.cache/charm/prometheus/2820601/layer/tmpccqcfccq: b"Cloning into '/home/knkski/.cache/charm/prometheus/2820601/layer/tmpccqcfccq'...\nwarning: templates not found /snap/charm/440/share/git-core/templates\n"
charmtools.fetchers: git rev-parse HEAD: b'a7d7b6423db37a47611310039e6ed1929c0a2eab\n'
charmtools.build.fetchers: Copying /home/knkski/.cache/charm/prometheus/2820601/layer/tmpccqcfccq to /home/knkski/.cache/charm/prometheus/2820601/layer/status
charmtools.build.fetchers: Cleaning up /home/knkski/.cache/charm/prometheus/2820601/layer/tmpccqcfccq
charmtools.build.fetchers: Checking layer index: https://juju.github.io/layer-index/interfaces/http.json
charmtools.build.fetchers: Found repo: https://github.com/juju-solutions/interface-http.git
charmtools.fetchers: git clone https://github.com/juju-solutions/interface-http.git /home/knkski/.cache/charm/prometheus/2820601/interface/tmp_kutaxky: b"Cloning into '/home/knkski/.cache/charm/prometheus/2820601/interface/tmp_kutaxky'...\nwarning: templates not found /snap/charm/440/share/git-core/templates\n"
charmtools.fetchers: git rev-parse HEAD: b'632131b1f122daf6fb601fd4c9f1e4dbb1a92e09\n'
charmtools.build.fetchers: Copying /home/knkski/.cache/charm/prometheus/2820601/interface/tmp_kutaxky to /home/knkski/.cache/charm/prometheus/2820601/interface/http
charmtools.build.fetchers: Cleaning up /home/knkski/.cache/charm/prometheus/2820601/interface/tmp_kutaxky
build: Processing layer: layer:options
build: Processing layer: layer:caas-base
build: Processing layer: layer:status
build: Processing layer: layer:docker-resource
build: Processing layer: prometheus (from charms/prometheus)
build: Processing interface: http
charmtools.build.tactics: Copying docker-resource: /home/knkski/charms/builds/prometheus/README.md
charmtools.build.tactics: Copying docker-resource: /home/knkski/charms/builds/prometheus/LICENSE
charmtools.build.tactics: Creating /home/knkski/charms/builds/prometheus/lib
charmtools.build.tactics: Creating /home/knkski/charms/builds/prometheus/lib/charms
charmtools.build.tactics: Creating /home/knkski/charms/builds/prometheus/lib/charms/layer
charmtools.build.tactics: Copying options: /home/knkski/charms/builds/prometheus/lib/charms/layer/options.py
charmtools.build.tactics: Creating /home/knkski/charms/builds/prometheus/bin
charmtools.build.tactics: Copying options: /home/knkski/charms/builds/prometheus/bin/layer_option
charmtools.build.tactics: Creating /home/knkski/charms/builds/prometheus/hooks
charmtools.build.tactics: Copying layer-caas-base: /home/knkski/charms/builds/prometheus/hooks/hook.template
utils: b'Traceback (most recent call last):\n  File "/snap/charm/440/bin/pip3", line 7, in <module>\n    from pip._internal.cli.main import main\nModuleNotFoundError: No module named \'pip._internal.cli.main\'\n'
utils: process: pip3 install -t /tmp/tmp3659nz9h -r /home/knkski/.cache/charm/prometheus/2820601/layer/caas-base/wheelhouse.txt (1)
Traceback (most recent call last):
  File "/snap/charm/440/bin/pip3", line 7, in <module>
    from pip._internal.cli.main import main
ModuleNotFoundError: No module named 'pip._internal.cli.main'

Command failed: pip3 install -t /tmp/tmp3659nz9h -r /home/knkski/.cache/charm/prometheus/2820601/layer/caas-base/wheelhouse.txt
```

**Comment by johnsca** [comment]
Unable to replicate this on my machine (focal), or on a fresh xenial or bionic lxd container.

**Comment by davecore82** [comment]
I'm hitting this issue as well:

`$ charm build src`
```
build: DEPRECATED: INTERFACE_PATH environment variable; please use CHARM_INTERFACES_DIR instead
build: DEPRECATED: LAYER_PATH environment variable; please use CHARM_LAYERS_DIR instead
build: Destination charm directory: /home/davecore/charms/builds/keystone-kerberos
build: Processing layer: layer:options
build: Processing layer: layer:basic
build: Processing layer: layer:openstack
build: Processing layer: keystone-kerberos (from src)
build: Processing interface: tls-certificates
build: Processing interface: keystone-fid-service-provider
build: Processing interface: juju-info
Traceback (most recent call last):
  File "/snap/charm/440/bin/virtualenv", line 5, in <module>
    from virtualenv.__main__ import run_with_catch
ModuleNotFoundError: No module named 'virtualenv.__main__'; 'virtualenv' is not a package


```Command failed: virtualenv --python python3 /tmp/tmpq6r_0wck


`$ snap list charm`
```
Name   Version  Rev  Tracking  Publisher   Notes
charm  2.7.3    440  stable    canonical✓  classic
```

**Comment by davecore82** [comment]
I also can't revert to the previous version of snap (I just reinstalled the snap charm with snap remove and snap install to troubleshoot this issue).

```
$ snap revert charm
error: cannot revert "charm": no revision to revert to
```

And I can't find another previous version either?

`$ snap info charm`
```
name:      charm
summary:   charm and charm-tools
publisher: Canonical✓
store-url: https://snapcraft.io/charm
contact:   juju@lists.ubuntu.com
license:   unset
description: |
  charmstore-client and charm-tools
commands:
  - charm
snap-id:      2Rryoc2ylScfbFl4eQtpntHD9iuZuMvt
tracking:     latest/stable
refresh-date: today at 15:07 EDT
channels:
  stable:    2.7.3 2020-03-05 (440) 116MB classic
  candidate: 2.7.3 2020-02-28 (440) 116MB classic
  beta:      2.7.3 2020-02-28 (440) 116MB classic
  edge:      2.7.3 2020-02-28 (440) 116MB classic
installed:   2.7.3            (440) 116MB classic

```

```
davecore@davecore-laptop:~/git/charm-keystone-kerberos$ snap list --all charm
Name   Version  Rev  Tracking  Publisher   Notes
charm  2.7.3    440  stable    canonical✓  classic
```

**Comment by johnsca** [comment]
> Running the virtualenv command of the snap manually fails too:
>
> `$ /snap/charm/440/bin/virtualenv --python python3 /tmp/tmpjz7z9tps`
> ```
> Traceback (most recent call last):
>   File "/snap/charm/440/bin/virtualenv", line 5, in <module>
>     from virtualenv.__main__ import run_with_catch
> ModuleNotFoundError: No module named 'virtualenv.__main__'; 'virtualenv' is not a package
> ```

This is entirely expected to fail because you're not running it inside the (albeit limited, due to classic) confinement of the snap.  If you instead run it within the snap's environment and include the env vars that the command wrapper sets up, it should work as intended:

```sh
$ /snap/charm/440/bin/virtualenv --python python3 /tmp/tmpjz7z9tps
Traceback (most recent call last):
  File "/snap/charm/440/bin/virtualenv", line 5, in <module>
    from virtualenv.__main__ import run_with_catch
ImportError: No module named 'virtualenv.__main__'; 'virtualenv' is not a package
$ snap run --shell charm
$ export PATH=$SNAP/bin:$SNAP/usr/bin:$SNAP/libexec/git-core:$PATH
$ export GIT_TEMPLATE_DIR=$SNAP/share/git-core/templates
$ export UNIXCONFDIR=$SNAP/etc
$ export PREFIX=$SNAP
$ export GIT_EXEC_PATH=$SNAP/usr/lib/git-core
$ export LC_ALL=C.UTF-8
$ /snap/charm/440/bin/virtualenv --python python3 /tmp/tmpjz7z9tps
created virtual environment CPython3.6.9.final.0-64 in 229ms
  creator CPython3Posix(dest=/tmp/tmpjz7z9tps, clear=False, global=False)
  seeder FromAppData(download=False, pip=latest, setuptools=latest, wheel=latest, via=copy, app_data_dir=/home/johnsca/.local/share/virtualenv/seed-app-data/v1)
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator
```

If that last example still fails for you, can you please also run `which python3` and `env` in that snap environment right after it fails and provide the full log of that?

The problem for me is that I still can't replicate this on any of my machines, which makes it very difficult for me to debug.  @sergiusens I don't suppose you can offer any insight?  It seems like it's somehow picking up the system python3 but only for some people, and I can't think of a way in which that might happen.

**Comment by davecore82** [comment]
@johnsca  it still fails, here are the details:  https://paste.ubuntu.com/p/X3FHszgJ9y/

**Comment by johnsca** [comment]
The issue seems to be in the difference you're seeing in the output from the following vs what I'm seeing (which is what I would expect):

```sh
[johnsca@murdoch:~/juju/envs/dev/charms/ubuntu] $ snap run --shell charm
[johnsca@murdoch:~ … arms/ubuntu] $ export PATH=$SNAP/bin:$SNAP/usr/bin:$SNAP/libexec/git-core:$PATH
[johnsca@murdoch:~ … arms/ubuntu] $ export GIT_TEMPLATE_DIR=$SNAP/share/git-core/templates
[johnsca@murdoch:~ … arms/ubuntu] $ export UNIXCONFDIR=$SNAP/etc
[johnsca@murdoch:~ … arms/ubuntu] $ export PREFIX=$SNAP
[johnsca@murdoch:~ … arms/ubuntu] $ export GIT_EXEC_PATH=$SNAP/usr/lib/git-core
[johnsca@murdoch:~ … arms/ubuntu] $ export LC_ALL=C.UTF-8
[johnsca@murdoch:~ … arms/ubuntu] $ $SNAP/usr/bin/python3 -c 'import virtualenv; print(virtualenv)'
<module 'virtualenv' from '/snap/charm/440/lib/python3.6/site-packages/virtualenv/__init__.py'>
```

**Comment by davecore82** [comment]
More information:

```
davecore@davecore-laptop:~$ snap run --shell charm
davecore@davecore-laptop:~$ export PATH=$SNAP/bin:$SNAP/usr/bin:$SNAP/libexec/git-core:$PATH
davecore@davecore-laptop:~$ export GIT_TEMPLATE_DIR=$SNAP/share/git-core/templates
davecore@davecore-laptop:~$ export UNIXCONFDIR=$SNAP/etc
davecore@davecore-laptop:~$ export PREFIX=$SNAP
davecore@davecore-laptop:~$ export GIT_EXEC_PATH=$SNAP/usr/lib/git-core
davecore@davecore-laptop:~$ export LC_ALL=C.UTF-8
davecore@davecore-laptop:~$ $SNAP/usr/bin/python3 -c 'import virtualenv; print(virtualenv)'
<module 'virtualenv' from '/home/davecore/.local/lib/python3.6/site-packages/virtualenv.py'>
```

**Comment by sergiusens** [comment]
This is `classic`, right? You might need to do something similar to https://github.com/snapcore/snapcraft/blob/master/tools/snapcraft-override-build.sh#L18

**Comment by davecore82** [comment]
Good news, I moved my ~/.local directory and I was able to build a charm. So there's something in .local that's causing this.

I had previously tried to just empty ~/.local/share/virtualenvs and ~/.local/share/virtualenv but I still had the error.

I moved the .local directory back after I built the charm. I'll try to see what specifically causes this behavior.

**Comment by davecore82** [comment]
It's actually just ~/.local/lib/python3.6/site-packages/virtualenv.py that I need to remove/rename.

If the file doesn't exist, the charm build works fine.

I'm not sure how ~/.local/lib/python3.6 got there in the first place.

**Comment by sergiusens** [comment]
You or something you ran did something of the likes of a `pip install --user <python-package>` which brought in `virtualenv`.

FWIW, my suggestion, applied to charm-tools itself, would disallow PYTHONUSERSITE

**Comment by johnsca** [comment]
This fix has been released to stable.
