### ISSUE TITLE
Charm build with missing `INTERFACE_PATH` cuases python traceback

### ISSUE THREAD

**Issue by mbruzek** [juju/charm-tools#56]
I was trying to build the openjdk layer and got an error.  it is unclear to me why the error occurred whether it was incorrect layer code or incorrect tool code.

```bash
mbruzek@warhorse:~/workspace/layers$ git clone git@github.com:juju-solutions/layer-openjdk
Cloning into 'layer-openjdk'...
remote: Counting objects: 20, done.
remote: Total 20 (delta 0), reused 0 (delta 0), pack-reused 20
Receiving objects: 100% (20/20), done.
Resolving deltas: 100% (6/6), done.
Checking connectivity... done.
mbruzek@warhorse:~/workspace/layers$ cd layer-openjdk/
mbruzek@warhorse:~/workspace/layers/layer-openjdk$ ls
config.yaml  copyright  layer.yaml  metadata.yaml  reactive  README.md
mbruzek@warhorse:~/workspace/layers/layer-openjdk$ export JUJU_REPOSITORY=/home/mbruzek/workspace/charms
mbruzek@warhorse:~/workspace/layers/layer-openjdk$ charm build
build: Composing into /home/mbruzek/workspace/charms
build: Processing layer: layer:basic
build: Processing layer: openjdk
build: Processing interface: java
Traceback (most recent call last):
  File "/usr/bin/charm-build", line 9, in <module>
    load_entry_point('charm-tools==1.9.3', 'console_scripts', 'charm-build')()
  File "/usr/lib/python2.7/dist-packages/charmtools/build/__init__.py", line 525, in main
    build()
  File "/usr/lib/python2.7/dist-packages/charmtools/build/__init__.py", line 423, in __call__
    self.generate()
  File "/usr/lib/python2.7/dist-packages/charmtools/build/__init__.py", line 388, in generate
    self.exec_plan(self.plan, self.layers)
  File "/usr/lib/python2.7/dist-packages/charmtools/build/__init__.py", line 360, in exec_plan
    cont &= tactic.lint()
TypeError: unsupported operand type(s) for &=: 'bool' and 'NoneType'
```

**Comment by mbruzek** [comment]
I am using charm tools version 1.9.3

Here is the details when running with charm build -l DEBUG

```
build: {
  "INTERFACE_PATH": null, 
  "JUJU_REPOSITORY": "/home/mbruzek/workspace/charms", 
  "LAYER_PATH": null, 
  "_charm": ".", 
  "_name": "openjdk", 
  "config": "<charmtools.build.config.BuildConfig object at 0x7fca7c52bd50>", 
  "deps": "/home/mbruzek/workspace/charms/deps", 
  "force": false, 
  "hide_metrics": false, 
  "interface_service": "http://interfaces.juju.solutions", 
  "log_level": "DEBUG", 
  "output_dir": "/home/mbruzek/workspace/charms", 
  "repo": "/home/mbruzek/workspace/charms/trusty", 
  "series": "trusty", 
  "target_dir": "/home/mbruzek/workspace/charms/trusty/openjdk"
}
charmtools.fetchers: git clone https://github.com/juju-solutions/reactive-base-layer.git /home/mbruzek/workspace/charms/deps/layer/tmp7mybkX: Cloning into '/home/mbruzek/workspace/charms/deps/layer/tmp7mybkX'...

```

**Comment by johnsca** [comment]
You don't have an `INTERFACE_PATH` set, and the java layer isn't in [interfaces.juju.solutions](http://interfaces.juju.solutions) yet.  This seems like an error reporting issue; we should catch unfound interfaces earlier and handle them better.

**Comment by johnsca** [comment]
I've added the java interface to the registry, so this particular example now works.  But the issue can be reproduced by specifying any dummy interface in a layer.
