### ISSUE TITLE
charm generate requires INTERFACE_PATH directories to be named exactly as interface

### ISSUE THREAD

**Issue by coreycb** [juju/charm-tools#57]
charm generate requires directories under INTERFACE_PATH to be named with the exact interface name and if not I get some ugliness (I'm testing a local interface that's not available on http://interfaces.juju.solutions/).

http://paste.ubuntu.com/13623744/

```
generate runtests: commands[0] | charm generate --log-level DEBUG -o /home/ubuntu/openstack-charm-layer-dev/build charm                                                                          [1143/2811]
build: {
  "INTERFACE_PATH": "/home/ubuntu/openstack-charm-layer-dev/interfaces", 
  "JUJU_REPOSITORY": "/home/ubuntu/openstack-charm-layer-dev/build", 
  "LAYER_PATH": null, 
  "_charm": "charm", 
  "_name": "testcharm", 
  "config": "<charmtools.build.config.BuildConfig object at 0x2b5d81f3b450>", 
  "deps": "/home/ubuntu/openstack-charm-layer-dev/build/deps", 
  "force": false, 
  "hide_metrics": false, 
  "interface_service": "http://interfaces.juju.solutions", 
  "log_level": "DEBUG", 
  "output_dir": "/home/ubuntu/openstack-charm-layer-dev/build", 
  "repo": "/home/ubuntu/openstack-charm-layer-dev/build/trusty", 
  "series": "trusty", 
  "target_dir": "/home/ubuntu/openstack-charm-layer-dev/build/trusty/testcharm"
}
charmtools.fetchers: git clone https://github.com/juju-solutions/reactive-base-layer.git /home/ubuntu/openstack-charm-layer-dev/build/deps/layer/tmpgeuNxA: Cloning into '/home/ubuntu/openstack-charm-layer
-dev/build/deps/layer/tmpgeuNxA'...

Traceback (most recent call last):
  File "/home/ubuntu/openstack-charm-layer-dev/.tox/generate/bin/charm-generate", line 9, in <module>
    load_entry_point('charm-tools==1.9.3', 'console_scripts', 'charm-generate')()
  File "/home/ubuntu/openstack-charm-layer-dev/.tox/generate/local/lib/python2.7/site-packages/charmtools/build/__init__.py", line 493, in deprecated_main
    main()
  File "/home/ubuntu/openstack-charm-layer-dev/.tox/generate/local/lib/python2.7/site-packages/charmtools/build/__init__.py", line 525, in main
    build()
  File "/home/ubuntu/openstack-charm-layer-dev/.tox/generate/local/lib/python2.7/site-packages/charmtools/build/__init__.py", line 423, in __call__
    self.generate()
  File "/home/ubuntu/openstack-charm-layer-dev/.tox/generate/local/lib/python2.7/site-packages/charmtools/build/__init__.py", line 386, in generate
    layers = self.fetch()
  File "/home/ubuntu/openstack-charm-layer-dev/.tox/generate/local/lib/python2.7/site-packages/charmtools/build/__init__.py", line 211, in fetch
    return self.fetch_deps(layer)
  File "/home/ubuntu/openstack-charm-layer-dev/.tox/generate/local/lib/python2.7/site-packages/charmtools/build/__init__.py", line 215, in fetch_deps
    self.fetch_dep(layer, results)
  File "/home/ubuntu/openstack-charm-layer-dev/.tox/generate/local/lib/python2.7/site-packages/charmtools/build/__init__.py", line 239, in fetch_dep
    iface = Interface(base, self.deps).fetch()
  File "/home/ubuntu/openstack-charm-layer-dev/.tox/generate/local/lib/python2.7/site-packages/charmtools/build/__init__.py", line 83, in fetch
    self.directory = path(fetcher.fetch(self.target_repo))
  File "/home/ubuntu/openstack-charm-layer-dev/.tox/generate/local/lib/python2.7/site-packages/charmtools/build/fetchers.py", line 79, in fetch
    res = f.fetch(dir_)
  File "/home/ubuntu/openstack-charm-layer-dev/.tox/generate/local/lib/python2.7/site-packages/charmtools/fetchers.py", line 188, in fetch
    shutil.copytree(self.path, dst, symlinks=True)
  File "/usr/lib/python2.7/shutil.py", line 208, in copytree
    raise Error, errors
shutil.Error: [(path(u'/home/ubuntu/openstack-charm-layer-dev/build/deps/interface/openstack-charm-layer-dev/build/deps/interface/openstack-charm-layer-dev/build/deps/interface/openstack-charm-layer-dev/b
uild/deps/interface/openstack-charm-layer-dev/build/deps/interface/openstack-charm-layer-dev/build/deps/interface/openstack-charm-layer-dev/build/deps/interface/openstack-charm-layer-dev/build/deps/interf
ace/openstack-charm-layer-dev/build/deps/interface/openstack-charm-layer-dev/build/deps/interface/openstack-charm-layer-dev/build/deps/interface/openstack-charm-layer-dev/build/deps/interface/openstack-ch
arm-layer-dev/build/deps/interface/openstack-charm-layer-dev/build/deps/interface/openstack-charm-layer-dev/build/deps/interface/openstack-charm-layer-dev/build/deps/interface/openstack-charm-layer-dev/bu
ild/deps/interface/openstack-charm-layer-dev/build/deps/interface/openstack-charm-layer-dev/build/deps/interface/openstack-charm-layer-dev/build/deps/interface/openstack-charm-layer-dev/build/deps/interfa
ce/openstack-charm-layer-dev/build/deps/interface/openstack-charm-layer-dev/build/deps/interface/openstack-charm-layer-dev/build/deps/interface/openstack-charm-layer-dev/build/deps/interface/openstack-cha
rm-layer-dev/build/deps/interface/openstack-charm-layer-dev/build/deps/interface/openstack-charm-layer-dev/build/deps/interface/openstack-charm-layer-dev/build/deps/interface/openstack-charm-layer-dev/bui
ld/deps/interface/openstack-charm-layer-dev/build/deps/interface/openstack-charm-layer-dev/build/deps/interface/openstack-charm-layer-dev/build/deps/interface/openstack-charm-layer-dev/build/deps/interfac
e/openstack-charm-layer-dev/build/deps/interface/openstack-charm-layer-dev/build/deps/interface/openstack-charm-layer-dev/build/deps/interface/openstack-charm-layer-dev/build/deps/interface/openstack-char
m-layer-dev/build/deps/interface/openstack-charm-layer-dev/build/deps/interface/openstack-charm-layer-dev/build/deps/interface/openstack-charm-layer-dev/build/deps/interface/openstack-charm-layer-dev/buil
d/deps/interface/openstack-charm-layer-dev/build/deps/interface/openstack-charm-layer-dev/build/deps/interface/openstack-charm-layer-dev/build/deps/interface/openstack-charm-layer-dev/build/deps/
```

It seems like looking through the interface.yaml files in each directory for the name key would make more sense and/or better error handling for the scenario.

**Comment by johnsca** [comment]
Some overlap with #56.

I'm actually not sure that we should be delving in and inspecting the `interface.yaml`, because then we open ourselves up to an issue similar to the one I have from time to time with `juju deploy` from a local repo, where if you have two charm directories with the same charm name in the `metadata.yaml` (e.g., if I renamed one to "$charm.old" for testing purposes), it will pick one at random and is neither consistent nor obvious.  In that case, I end up with what looks like a successful deploy, but it's using the wrong charm code (or would use the wrong interface code, in this case), which is hard to spot and can cause subtle bugs.

We could sort of work around this by sorting the directory names when performing the search so that it's at least consistent, but personally I'd lean toward just keeping the strict name requirement (and simpler implementation) and just catch and report "interface not found" errors better.

**Comment by coreycb** [comment]
An "interface not found" error would be fine with me.

**Comment by johnsca** [comment]
Closing in favor of #56, then.
