### ISSUE TITLE
charm build includes arch-specific wheels

### ISSUE THREAD

**Issue by kwmonroe** [juju/charm-tools#58]
I did 'charm build' from charm-tools-1.9.3-0ubuntu1~ubuntu14.04.1~ppa1 on this source:

https://code.launchpad.net/~azulcharmers/charms/trusty/zulu8/trunk

I did this on a ppc64le box.  The built charm includes apparently ppc-specific stuff:

```
$ tree wheelhouse/ | grep ppc                        
├── MarkupSafe-0.23-cp27-none-linux_ppc64le.whl
├── PyYAML-3.11-cp27-none-linux_ppc64le.whl
```

Now when I attempt to deploy this local charm to Azure (with x86 units), I get this:

```
unit-zulu8-0[17465]: 2015-12-03 15:52:16 INFO unit.zulu8/0.install logger.go:40 Successfully installed pip
unit-zulu8-0[17465]: 2015-12-03 15:52:16 INFO unit.zulu8/0.install logger.go:40 Cleaning up...
unit-zulu8-0[17465]: 2015-12-03 15:52:16 INFO unit.zulu8/0.install logger.go:40 Ignoring indexes: https://pypi.python.org/simple
unit-zulu8-0[17465]: 2015-12-03 15:52:17 INFO unit.zulu8/0.install logger.go:40 MarkupSafe-0.23-cp27-none-linux_ppc64le.whl is not a supported wheel on this platform.
unit-zulu8-0[17465]: 2015-12-03 15:52:17 INFO unit.zulu8/0.install logger.go:40 Traceback (most recent call last):
unit-zulu8-0[17465]: 2015-12-03 15:52:17 INFO unit.zulu8/0.install logger.go:40   File "/var/lib/juju/agents/unit-zulu8-0/charm/hooks/install", line 18, in <module>
unit-zulu8-0[17465]: 2015-12-03 15:52:17 INFO unit.zulu8/0.install logger.go:40     check_call(['pip', 'install', '-U', '--no-index'] + glob('wheelhouse/*'))
unit-zulu8-0[17465]: 2015-12-03 15:52:17 INFO unit.zulu8/0.install logger.go:40   File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
unit-zulu8-0[17465]: 2015-12-03 15:52:17 INFO unit.zulu8/0.install logger.go:40     raise CalledProcessError(retcode, cmd)
unit-zulu8-0[17465]: 2015-12-03 15:52:17 INFO unit.zulu8/0.install logger.go:40 subprocess.CalledProcessError: Command '['pip', 'install', '-U', '--no-index', 'wheelhouse/pip-7.1.2-py2.py3-none-any.whl', 'wheelhouse/netaddr-0.7.18-py2-none-any.whl', 'wheelhouse/MarkupSafe-0.23-cp27-none-linux_ppc64le.whl', 'wheelhouse/PyYAML-3.11-cp27-none-linux_ppc64le.whl', 'wheelhouse/Jinja2-2.8-py2.py3-none-any.whl', 'wheelhouse/charmhelpers-0.6.0-py2-none-any.whl', 'wheelhouse/charms.reactive-0.3.6-py2-none-any.whl', 'wheelhouse/pyaml-15.8.2-py2-none-any.whl', 'wheelhouse/Tempita-0.5.2-py2-none-any.whl', 'wheelhouse/six-1.10.0-py2.py3-none-any.whl']' returned non-zero exit status 1
```

Does charm-build need to support something like "target arch" so it can include the correct arch-dependent deps?  Or should these all be noarch -- specifically MarkupSafe and PyYAML?

**Comment by johnsca** [comment]
This seems to completely contradict the documentation of the `--no-binary :all:` option that we use.  There is a deprecated `--no-use-wheel` that we could perhaps use, but that doesn't seem like a good long-term solution.  We should probably open an issue upstream for this.
