### ISSUE TITLE
charm-build --use-lock-file-branches fails to build if there is no branch recorded in the build.lock for a layer/interface

### ISSUE THREAD

**Issue by ajkavanagh** [juju/charm-tools#603]
## Checklist

 - [X] Confirmed this is an issue with charm-tools, not charmstore-client
 - [X] Provide versions of tools used
 - [X] Described the feature or ways to replicate the issue

## What version am I running?

~I ran the following command: `snap info charm` and got the following ouput:~

I'm using the PiPy version: "charm-tools 2.8.3"

I am using: Ubuntu 20.04

## Issue/Feature

The charm-build command with --write-lock-file built a lock file for `interface:ceph-mds` with:

```json
    {
      "type": "layer",
      "item": "interface:ceph-mds",
      "url": "https://opendev.org/openstack/charm-interface-ceph-client.git",
      "vcs": null,
      "branch": null,
      "commit": "72245e1d002fb9c65c9574d65b5952275b3411fb"
    },
```

### I expect/expected the following

When rebuilding with `--use-lock-file-branches`, I'd expect it to ignore the `null` branch and use the commit hash instead.

### What I got

charm-build crashed with:

```
make_url_from_lock_for_layer: {'type': 'layer', 'item': 'interface:ceph-mds', 'url': 'https://opendev.org/openstack/charm-interface-ceph-client.git', 'vcs': None, 'branch': None, 'commit': '72245e1d002fb9c65c9574d65b5952275b3411fb'} True
Traceback (most recent call last):
  File "/home/alex/Projects/Canonical/git/github.com/juju/charm-tools/venv/bin/charm-build", line 11, in <module>
    load_entry_point('charm-tools', 'console_scripts', 'charm-build')()
  File "/home/alex/Projects/Canonical/git/github.com/juju/charm-tools/charmtools/build/builder.py", line 1195, in main
    build()
  File "/home/alex/Projects/Canonical/git/github.com/juju/charm-tools/charmtools/build/builder.py", line 834, in __call__
    self.generate()
  File "/home/alex/Projects/Canonical/git/github.com/juju/charm-tools/charmtools/build/builder.py", line 771, in generate
    layers = self.fetch()
  File "/home/alex/Projects/Canonical/git/github.com/juju/charm-tools/charmtools/build/builder.py", line 306, in fetch
    return self.fetch_deps(self.top_layer)
  File "/home/alex/Projects/Canonical/git/github.com/juju/charm-tools/charmtools/build/builder.py", line 311, in fetch_deps
    self.fetch_dep(layer, results)
  File "/home/alex/Projects/Canonical/git/github.com/juju/charm-tools/charmtools/build/builder.py", line 343, in fetch_dep
    results["interfaces"].append(iface.fetch())
  File "/home/alex/Projects/Canonical/git/github.com/juju/charm-tools/charmtools/build/builder.py", line 99, in fetch
    url = make_url_from_lock_for_layer(
  File "/home/alex/Projects/Canonical/git/github.com/juju/charm-tools/charmtools/build/builder.py", line 982, in make_url_from_lock_for_layer
    if branch.startswith("refs/heads/"):
AttributeError: 'NoneType' object has no attribute 'startswith'
```

(Extra debug added at top to work out what was going on).

I'll file a separate bug as to why the option `--write-lock-file` didn't pick up the branch (which should be `refs/heads/master`) for the interface.

**Comment by fnordahl** [comment]
Fixed by #607
