### ISSUE TITLE
charm build fails w/o git

### ISSUE THREAD

**Issue by johnsca** [juju/charm-tools#76]
Installing charm-tools from the PPA doesn't include git as a dependency or a recommend:

```
dlawson@ubuntu-metal:~/work/branches/charms/layers/django$ sudo apt-get update && sudo apt-get install charm-tools
<snipped update out>
The following packages were automatically installed and are no longer required:
  linux-headers-4.2.0-16 linux-headers-4.2.0-16-generic linux-image-4.2.0-16-generic linux-image-extra-4.2.0-16-generic
Use 'apt-get autoremove' to remove them.
The following extra packages will be installed:
  python-blessings python-chardet-whl python-charmworldlib python-colander python-colorama python-colorama-whl python-distlib
  python-distlib-whl python-html5lib-whl python-jujubundlelib python-otherstuf python-parse python-path.py python-pathspec python-pip
  python-pip-whl python-requests-whl python-ruamel.base python-ruamel.ordereddict python-ruamel.std.argparse python-ruamel.yaml
  python-setuptools-whl python-six-whl python-stuf python-translationstring python-urllib3-whl python-virtualenv python-wheel
  python3-virtualenv virtualenv
Recommended packages:
  python-dev-all
The following NEW packages will be installed:
  python-blessings python-chardet-whl python-charmworldlib python-colander python-colorama python-colorama-whl python-distlib
  python-distlib-whl python-html5lib-whl python-jujubundlelib python-otherstuf python-parse python-path.py python-pathspec python-pip
  python-pip-whl python-requests-whl python-ruamel.base python-ruamel.ordereddict python-ruamel.std.argparse python-ruamel.yaml
  python-setuptools-whl python-six-whl python-stuf python-translationstring python-urllib3-whl python-virtualenv python-wheel
  python3-virtualenv virtualenv
The following packages will be upgraded:
  charm-tools
1 upgraded, 30 newly installed, 0 to remove and 0 not upgraded.
Need to get 1,622 kB of archives.
After this operation, 7,203 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
```

But if you try to run charm build without it, you get a nasty traceback:

```
dlawson@ubuntu-metal:~/work/branches/charms/layers/django$ charm build -l DEBUG
build: Composing into /home/dlawson/work/branches/charms/
build: {
  "INTERFACE_PATH": null, 
  "JUJU_REPOSITORY": "/home/dlawson/work/branches/charms/", 
  "LAYER_PATH": null, 
  "_charm": ".", 
  "_name": "django", 
  "config": "<charmtools.build.config.BuildConfig object at 0x7f2adeb4cb90>", 
  "deps": "/home/dlawson/work/branches/charms/deps", 
  "force": false, 
  "hide_metrics": false, 
  "interface_service": "http://interfaces.juju.solutions", 
  "log_level": "DEBUG", 
  "output_dir": "/home/dlawson/work/branches/charms/", 
  "repo": "/home/dlawson/work/branches/charms/trusty", 
  "series": "trusty", 
  "target_dir": "/home/dlawson/work/branches/charms/trusty/django"
}
Traceback (most recent call last):
  File "/usr/bin/charm-build", line 9, in <module>
    load_entry_point('charm-tools==1.10.1', 'console_scripts', 'charm-build')()
  File "/usr/lib/python2.7/dist-packages/charmtools/build/__init__.py", line 532, in main
    build()
  File "/usr/lib/python2.7/dist-packages/charmtools/build/__init__.py", line 429, in __call__
    self.generate()
  File "/usr/lib/python2.7/dist-packages/charmtools/build/__init__.py", line 392, in generate
    layers = self.fetch()
  File "/usr/lib/python2.7/dist-packages/charmtools/build/__init__.py", line 215, in fetch
    return self.fetch_deps(layer)
  File "/usr/lib/python2.7/dist-packages/charmtools/build/__init__.py", line 219, in fetch_deps
    self.fetch_dep(layer, results)
  File "/usr/lib/python2.7/dist-packages/charmtools/build/__init__.py", line 243, in fetch_dep
    iface = Interface(base, self.deps).fetch()
  File "/usr/lib/python2.7/dist-packages/charmtools/build/__init__.py", line 87, in fetch
    self.directory = path(fetcher.fetch(self.target_repo))
  File "/usr/lib/python2.7/dist-packages/charmtools/build/fetchers.py", line 79, in fetch
    res = f.fetch(dir_)
  File "/usr/lib/python2.7/dist-packages/charmtools/fetchers.py", line 144, in fetch
    git('clone {} {}'.format(url, dir_))
  File "/usr/lib/python2.7/dist-packages/charmtools/fetchers.py", line 294, in git
    check_call('git ' + cmd, **kw)
  File "/usr/lib/python2.7/dist-packages/charmtools/fetchers.py", line 302, in check_call
    return check_output(cmd, **kw)
  File "/usr/lib/python2.7/dist-packages/charmtools/fetchers.py", line 315, in check_output
    **kw
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by johnsca** [comment]
Since most of our layers are in git repos now, I think having the `git` package as a hard dep. is a good idea.

**Comment by marcoceppi** [comment]
What other source control tools should be included?

**Comment by johnsca** [comment]
The layers support any of the fetchers in charmtools.fetchers.  Should we support all of those (looks like git, bzr, and hg) out of the box?  Another approach to this would be to handle the error better, but then I feel like we would have users wondering why they had to handle the VCS deps manually.

**Comment by marcoceppi** [comment]
I'll make these explicit in the packaging for Debian and Homebrew.

**Comment by marcoceppi** [comment]
Packaging updated
