### ISSUE TITLE
Bundle proof is not robust when encountering missing keys

### ISSUE THREAD

**Issue by bac** [juju/charm-tools#89]
Helping a user debug a bundle that was not ingested I saw the following:

```
[openstack-calico]bac@salchicha:~/bundles/openstack-calico$ juju bundle proof
Traceback (most recent call last):
  File "/usr/bin/charm-proof", line 9, in <module>
    load_entry_point('charm-tools==1.11.0', 'console_scripts', 'charm-proof')()
  File "/usr/lib/python2.7/dist-packages/charmtools/proof.py", line 71, in main
    args_.secure)
  File "/usr/lib/python2.7/dist-packages/charmtools/proof.py", line 63, in proof
    remote=with_remote, server=server, port=port, secure=secure)
  File "/usr/lib/python2.7/dist-packages/charmtools/bundles.py", line 127, in proof
    lint.local_proof(self)
  File "/usr/lib/python2.7/dist-packages/charmtools/bundles.py", line 56, in local_proof
    self.validate(bdata, name)
  File "/usr/lib/python2.7/dist-packages/charmtools/bundles.py", line 32, in validate
    if not charm_url_includes_id(sdata['charm']):
KeyError: 'charm'
```

For at least one service the user failed to include the 'charm' key. The code here should be more defensive and report an error not a traceback.

**Comment by marcoceppi** [comment]
Agreed, we will have a patch out Monday to address this and make it more
robust.
